### ISSUE TITLE
`.asJsonSchema` method

### ISSUE THREAD

**Issue by aymericbouzy** [colinhacks/zod#1039]
Some places require to describe input and output as a JSON schema.

Would a feature that exports as JSON schema be welcome? 

```ts
z.object({
  a: z.string().optional(),
}).asJsonSchema();
```
would give
```js
{
  type: "object",
  properties: {
    a: { type: "string" },
  },
}
```

**Comment by FlorianWendelborn** [comment]
I think this is not needed as it’s provided by the ecosystem already: <https://github.com/StefanTerdell/zod-to-json-schema>

While I’ve never used `zod-to-json-schema`, my assumption would be that it works well enough. IMO, it makes more sense to put efforts into making that project better rather than duplicating it.

However, maybe @colinhacks has a different opinion about this feature.

**Comment by aymericbouzy** [comment]
Thanks! That makes total sense of course, i should have googled that myself 🙏
