### ISSUE TITLE
Shorter way to validate boolean from string "true" / "false" / overwrite a schema

### ISSUE THREAD

**Issue by rottmann** [colinhacks/zod#1055]
e.g. you call a rest-api endpoint with `//some/endpoint?isVisible=true`
The server receives a string `isVisible = 'true'`

How you validate it in a shorter way?

```
const isVisibleSchema = z.union([ z.literal('true'), z.literal('false') ]).optional().transform( (val) => val === 'true') // overkill

const humanReadableWouldBe = z.boolean().optional() // not work, cause it is a string
```

Is there a way to extend / overwrite z.boolean?

**Comment by FlorianWendelborn** [comment]
I’d use `z.preprocess` for this. Just do:

```ts
import { z } from 'zod'

const stringToBoolean = (value: unknown) => {
    switch (value) {
        case "true":
        case "TRUE":
        case "1":
            return true
            
        case "false":
        case "FALSE":
        case "0":
            return false

        default:
            return undefined
    }
}

const schema = z.preprocess(stringToBoolean, z.boolean()).optional()
```

And then just put your utility functions like `stringToBoolean` into a dedicated file. E.g. `utilities/zod-preprocess.ts`

**Comment by rottmann** [comment]
Coherent diskussion: #804

@FlorianWendelborn Thx, had some similar solution.

**Comment by ryanhaticus** [comment]
Please see coercion: https://github.com/colinhacks/zod#coercion-for-primitives

**Comment by FlorianWendelborn** [comment]
@ryanhaticus coercion is likely **not** a good idea here since it's literally just a `Boolean` cast. Here's one example where it likely produces the opposite of what you'd expect in the API proposed by OP

![image](https://user-images.githubusercontent.com/1133858/217527232-8e60e944-ae5b-4e70-b755-0499c8b52b5d.jpeg)

I'd personally still recommend using a preprocess utility similar to the one I posed above as it doesn't have these unexpected behaviors, so no need to re-open this ticket
