### ISSUE TITLE
Cannot assign a 'private' constructor type to a 'public' constructor type

### ISSUE THREAD

**Issue by michaelmerrill** [colinhacks/zod#1065]
I'd like to ensure that the `to` and `from` property are of the TransactionAmount class. The TransactionAmount class has it's own validation and I figure it can do the validation and creation before being passed in as props here. Is this the right way to do that?

```
export const transactionProps = z.object({
  id: z.string(),
  to: z.instanceof(TransactionAmount), // Argument of type 'typeof TransactionAmount' is not assignable to parameter of type 'new (...args: any[]) => any'. Cannot assign a 'private' constructor type to a 'public' constructor type.
  from: z.instanceof(TransactionAmount), // same.
});
```

```
export const transactionAmountProps = z.object({
  amount: z.string(),
  currency: z.string(),
});

export type TransactionAmountProps = z.infer<typeof transactionAmountProps>;

export class TransactionAmount {
  private constructor(private readonly props: TransactionAmountProps) {}

  get amount(): string {
    return this.props.amount;
  }

  get currency(): string {
    return this.props.currency;
  }

  public static create(props: TransactionAmountProps): Result<TransactionAmount, TransactionValidationError> {
    const validation = transactionAmountProps.safeParse(props);

    if (!validation.success) {
      return Err(new TransactionValidationError(JSON.stringify(validation.error.format())));
    }

    return Ok(new TransactionAmount(validation.data));
  }
}
```

**Comment by colinhacks** [comment]
Not much I can do about this. Without a public constructor there's no way for TypeScript to validate that the argument to `z.instanceof` is actually a class. 

Here's the workaround (this is what `z.instanceof` does under the hood anyway):

```ts
const txSchema = z.custom< TransactionAmount >(arg => arg instanceof TransactionAmount)
```

**Comment by Fryuni** [comment]
Typescript allows `instanceof` on anything that implements `NewableFunction`, the constructor type implies that, but it is more restrictive than it needs. In fact if you pass a function with a private constructor and ignores typescript it works.

What could be done is provide a separate `unsafeInstanceOf<T extends NewableFunction>`.

Why make it a new function and call it unsafe instead of changing the existing one?

Because if you pass any class with a protected or private constructor there are cases where TS will reduce the type to any because there is no way to properly refer to "an instance of this type that has a private constructor". So it works exactly as anyone would expect, but the type may become any.
