### ISSUE TITLE
Feature request: set discriminator field

### ISSUE THREAD

**Issue by lobotomoe** [colinhacks/zod#1072]
I have two schemas that doesn't have common property (discriminator).
I have no chance to change input data, this is external data.

I know that I can handle it this way:

```ts
const swapInfoSchema = z.union([
  z.preprocess((content) => ({ ... content, type: 'byAmountIn'}), swapInfoByAmountIn)
  z.preprocess((content) => ({ ... content, type: 'byAmountOut'}), swapInfoByAmountOut)
]);
```

But `content` is unknown and a don't want set `any` type here.

Also I thought that I can do:

```ts
const swapInfoByAmountOut = swapInfoBase.extend({
  availableAmountOut: z.number(),
  availableAmountIn: z.null(),
  marketAmountOut: z.null(),
  marketAmountIn: z.number().nullable(),
}).transform((val) => ({
  ...val,
  type: 'byAmountOut' as const,
}));
```

But inferred type doesn't contain my "type" field. Any suggestions?

**Comment by scotttrinh** [comment]
@lobotomoe 

I do something similar to your `transform` example in a bunch of places and the inferred type _is_ correct for me. Can you post a more complete example maybe as a CodeSandbox or TypeScript playground?

You're definitely using `z.infer` or `z.output` as your type inference method, right? `z.input` would return the non-transformed type rather than the output type like `infer`/`output`.

**Comment by lobotomoe** [comment]
@scotttrinh 

My example here: https://codesandbox.io/s/typescript-playground-export-forked-96mw33?file=/index.ts

See the `getInfo` function.

**Comment by scotttrinh** [comment]
Played around with it a bit and it turns out that the schema type needed to allow for variation between the input and output types:

[CodeSandbox](https://codesandbox.io/s/typescript-playground-export-forked-3t6gvj)

```ts
const fetchJsonWithValidation = async <Out, In>(
  url: string,
  schema: Schema<Out, z.ZodTypeDef, In>
) => {
  const response = await fetch(url);
  const json = await response.json();
  return schema.parse(json);
};
```

Going to close for now, but if there are any follow-up issues or questions, feel free to re-open and add to this ticket.
