### ISSUE TITLE
Request: ZodDate min and max

### ISSUE THREAD

**Issue by mrichards42** [colinhacks/zod#1089]
I'm happy to give this a shot myself if you think it's worthwhile to add!

I get that this can currently be achieved with a refinement:

```js
z.date().refine((d) => d >= new Date("2020-01-01") && d <= new Date("2030-01-01"))
```

... but it seems like a reasonable top-level concept to me:

```js
z.date().min(new Date("2020-01-01")).max(new Date("2030-01-01"))
```

**Comment by Svish** [comment]
Wanting to use `zod` instead of `yup`, but I'm really missing this feature as well. We're dealing with several forms, most of them have at least one date field, and I don't think a single one of them are without a minimum or a maximum date. It's basically always "pick a date in the past" (like, a date of birth) or "pick a date in the future" (like, when do you need this thing you're requesting).

If it for some reason won't be added to the library, maybe because you don't want to tie it to a specific date-library, which is fair, it would at least be good if there were good examples in the docs about how to do it with a few common date-libraries.

**Comment by scotttrinh** [comment]
Seems reasonable! If someone wants to take this on, I'd support adding `min` and `max` methods to `ZodDate` and should be pretty straightforward.

**Comment by Balastrong** [comment]
Hey, I just pushed a PR for this!

That's my first PR around here so feel free to let me know if something is wrong/missing or if there are suggestions :)

**Comment by Svish** [comment]
@Balastrong Awesome! I don't have any power of these PR's, like actual acceptance, merging, or release, but did a review and gave some comments of things I think should be changed, to make it more "in line" with my `zod` experience so far.

* `min` and `max` should be inclusive, to match the behavior of e.g. `min` and `max` for `number`
* the generated error messages shouldn't be hard-coded to `inclusive: true` or `inclusive: false`, since these error messages can be generated by others too, not just the built-in checks.

**Comment by Balastrong** [comment]
The check was already inclusive by default but indeed it wasn't properly handled in the code. I update the PR, thank you for pointing it out! :)

**Comment by evilive3000** [comment]
Unfortunately, I don't see any real practical use of this feature in any dynamic system.

It would be very convenient to pass a function instead of a static date value.

For example, 
```
expireAt: z.coerce.date().min(Date.now);
```
or
```
const HOUR = 3600_000;
expireAt: z.coerce.date().min(() => Date.now() + HOUR);
```

I wonder who actually uses the current implementation, and what your usecases are?

**Comment by Svish** [comment]
@evilive3000 We're using it. I agree that it would be much more dynamic if you could pass in a function like you describe, but for us it works as it is too.

Usually we're doing something along the lines of `z.date().min(startOfToday())` or `z.date().max(endOfYesterday())` (using `date-fns`), and this is plenty good enough as it's very unlikely that a user will be sitting on a single form, mid filling it out, not submitting it, until over a day later has passed. And if they do, they will most likely have been timed out by the auth, and will need to reload the page anyways, which would recreate the validation schema with an updated min/max date.

If you need it to be more dynamic, I'd recommend that you create a separate issue for this, and maybe also submit a PR with the change. Personally I think it would be an improvement, but don't know what the maintainers of `zod` think. Create an issue and/or a PR and you'll probably find out.  😊👍
