### ISSUE TITLE
Stricter types

### ISSUE THREAD

**Issue by fxdave** [colinhacks/zod#1101]
Hi! Thanks for the library.

I'd like to request a feature because currently it is missing so much.

The errors are barely typed, so for example when I return a custom error with a `path` that has absolutely no connection with the schema, ts does warn me.
```ts
const schema = z.object({
    smscode: z.string()
});

// after schema validation passes: 
const customValidationIssue = {
    code: "custom",
    path: ["password"], // this should be smscode, but TS accepts password currently.
    message: "Wrong password",
} as z.ZodIssue;
```

Because the `smscode` is z.string() only, I think it will not throw for example ZodTooBigIssue. But ZodTooBigIssue and other unreachable errors are parts of the ZodIssue type so it is misleading. 

I would like to see more generic types.

**Comment by scotttrinh** [comment]
Let me see if I understand your issue correctly:

1. `ZodIssue.path` is not constrained and is just an array of strings that might be incorrect.
2. Individual schemas do not refine the possible `ZodIssue` subtypes meaning that a schema cannot throw a particular kind of issue, but the compiler doesn't know that so it is present at the type level even if it's unreachable.

Is that a fair summary of your points?

---

To address the first point about `path`, I don't think there is a straightforward way to constrain that since schemas can be deeply nested, so there is an exponential number of possible valid combinations of strings, and in the case of recursive schemas, an infinite number. Probably the only thing we could do that was any better than `string[]` here is to have a union of all deeply nested object keys, but I'm not sure if we can even support that in the recursive case.

For the second, I think it's more of a practical concern, since, as your example proves, `ZodString` does indeed have a case where it uses that error in the case of `z.string().max(n)`. It's probably more trouble than it's worth to define the one or two errors that cannot be returned and make sure to keep those in sync, but I think we would explore a PR that added that if you're interested in contributing.

**Comment by fxdave** [comment]
That's fair summary yes.

I've just created the Path type based on react-hook-form's implementation for the similar Path type.
```ts

// Utility types
type ArrayKey = number
type Primitive = null | undefined | string | number | boolean | symbol | bigint;
/** Cons<'a', ['b', 'c']> => ['a', 'b', 'c']*/
type Cons<H, T extends readonly any[]> =
    ((h: H, ...t: T) => void) extends ((...r: infer R) => void) ? R : never
/** TupleKeys<['a', 'b']> => 0 | 1 */
type TupleKeys<T extends ReadonlyArray<any>> = Exclude<keyof T, keyof any[]>;
/** IsTuple<[number, number]> => true, IsTuple<number[]> = false */
type IsTuple<T extends ReadonlyArray<any>> = number extends T['length'] ? false : true;
/** PathImpl<'foo', { bar: ['a'] }> => ["foo"] | ["foo", "bar"] | ["foo", "bar", "0"] */
type PathImpl<K extends string | number, V> = V extends Primitive ? [K] : [K] | Cons<K, Path<V>>;
/** Path<{ foor: { bar: ['a', 'b'] }}> => ["foo"] | ["foo", "bar"] | ["foo", "bar", "0"] | ["foo", "bar", "1"] */
type Path<T> = T extends ReadonlyArray<infer V> ? IsTuple<T> extends true ? {
    [K in TupleKeys<T>]-?: PathImpl<K & string, T[K]>;
}[TupleKeys<T>] : PathImpl<ArrayKey, V> : {
    [K in keyof T]-?: PathImpl<K & string, T[K]>;
}[keyof T];

export type ImprovedZodIssue<TInferredSchema extends Record<string, unknown>> = ZodIssue &
    { path: Path<TInferredSchema> }
```
