### ISSUE TITLE
enum of numbers

### ISSUE THREAD

**Issue by amatiasq** [colinhacks/zod#1118]
This code fails:

```ts
import { z } from "zod";

const Multipliers = [1, 2, 3, 4] as const;

const schema = z.enum(Multipliers);
```

With error

```
No overload matches this call.
  Overload 1 of 2, '(values: readonly [string, ...string[]]): ZodEnum<[string, ...string[]]>', gave the following error.
    Argument of type '[1, 2, 3, 4, 5, 6]' is not assignable to parameter of type 'readonly [string, ...string[]]'.
      Type at position 0 in source is not compatible with type at position 0 in target.
        Type 'number' is not assignable to type 'string'.
  Overload 2 of 2, '(values: [string, ...string[]]): ZodEnum<[string, ...string[]]>', gave the following error.
    Argument of type '[1, 2, 3, 4, 5, 6]' is not assignable to parameter of type '[string, ...string[]]'.
      Type at position 0 in source is not compatible with type at position 0 in target.
        Type 'number' is not assignable to type 'string'.ts(2769)
```

Is there any reason why `z.enum` only expects `string`s?

https://codesandbox.io/s/zod-number-union-4pqezv

**Comment by TheoBr** [comment]
This would be very useful for us at Ping

**Comment by amatiasq** [comment]
Well it is staled but it's not "completed" :\

**Comment by joshuat** [comment]
For anyone else running into this problem, this is how I worked around the limitation in `z.enum`:

```ts
import { z } from 'zod';
import type { ZodLiteral } from 'zod';

export const LIMIT_OPTIONS = [10, 25, 50] as const;

export function numericEnum<
  TValues extends readonly [number, number, ...number[]],
>(values: TValues) {
  const options = values.map((value) =>
    z.literal(value),
  ) as unknown as Readonly<{
    [I in keyof TValues]: ZodLiteral<TValues[I]>;
  }>;
  return z.union(options);
}

const TestSchema = z.object({
  property: numericEnum(LIMIT_OPTIONS),
});

export type Test = z.infer<typeof TestSchema>;
```

[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQokscMAnmAKaJwBaJAMsDE1AIYAbdFhx5CJchQpMAHjXgBjCADsAzvE4BJALJaAKgH0A8gAV9W4wDkAynAC8cANoBGAAwAaOACYArF983AF04fjU4ZXUYShl5aHhMAFcVRRhgVTgVRJA+YEUAUSyQAB4KODh9ADUhRKZwuV4VYnCoJn5iVUF6ZyKAIz4vPoG4ADoxoagnIKCPCgA+AAoANxq6gC4K6sFatQBKRDKI1Q04CDA044c4Fe26kZB+MAXl1f37OcPy5BHBHj4hF63Xazcr7MJwZIAaxUEAA7ipQuEAEptDoqLrFBCfZxaODABGQpj0CCYTarNRBDYcYjcXgCQTFKrkpxaIJzSjlNDsw6tGCJKAI77JdIqBZnC7qXaUNDSSInfR1GA2RQACyYDyu3wgvQAVkxUgsseUwDhmLB6BsirkCkUFto9EYzBZrDZgRQ0FLpHIFHRGCwFSdHN98Zg+MUGMwSRVFcq1Q9uUA)

Biggest downside is that it will only work when there are 3 or more options, this is due to a type restriction in `z.union`.

**Comment by joshuat** [comment]
@colinhacks Would you be open to a PR to add number support to enums? I know it isn't a 1:1 with the TypeScript definition of an enum, but this is in practice much more akin to a union (that's even what it infers to) than it is an enum in the TypeScript sense.

**Comment by sylvainbaronnet** [comment]
Hey, would be nice to have that

**Comment by sylvainbaronnet** [comment]
I think we can at least re-open this issue

**Comment by sgpinkus** [comment]
A work around is like `z.union([z.literal(-1), z.literal(1)])`

**Comment by stormynight9** [comment]
any official updates on this?

**Comment by Moustafa3attia** [comment]
Thought this might help: https://zod.dev/?id=native-enums

**Comment by bernaferrari** [comment]
Sometimes all I wish is `z.enum<T>` or something like that, so that is generic enough to support numbers/other things.
