### ISSUE TITLE
Union of z.literal() numbers

### ISSUE THREAD

**Issue by DNoel26** [colinhacks/zod#1138]
How would you go about doing this? 

```
const union = z.union(
    [1, 2, 3, 4, 5].map((val) => z.literal(val)),
)
-----------------------------------------------------
const arr = [1, 2, 3, 4, 5] as const
const union = z.union(
    arr.map((val) => z.literal(val)),
)
```

Neither works with the type system. 

```
Argument of type 'ZodLiteral<number>[]' is not assignable to 
parameter of type 'readonly [ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]'.
Source provides no match for required element at position 0 in target.
------------------------------------------------------------------------------------
Argument of type 'ZodLiteral<0.166667 | 0.2 | 0.25>[]' is not assignable to 
parameter of type 'readonly [ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]'.
Source provides no match for required element at position 0 in target.
```

I've tried using refine which works but gives me inferred type 'number' instead of 1 | 2 | 3 | 4 | 5.

**Comment by CGamesPlay** [comment]
Zod requires that the argument to `z.union` is a tuple because otherwise it can't properly infer the types of the input/result. TypeScript does not support `Array.map` on tuples. You could [use a mapped type](https://stackoverflow.com/questions/57913193/how-to-use-array-map-with-tuples-in-typescript) to achieve this, or you could just list the options statically:

```typescript
const union = z.union([z.literal(1), z.literal(2), ...]);
```
