### ISSUE TITLE
Zod schema from OpenAPI/Swagger

### ISSUE THREAD

**Issue by gius** [colinhacks/zod#1151]
Is there a way to generate Zod schema from OpenAPI/Swagger definition? 
I could not find anything related (there are many tools for the other way), but I guess that validating/converting JSON from API would be a typical Zod use case.

**Comment by scotttrinh** [comment]
Yeah, I think there are a lot of solutions that way due to wanting zod to be the source of truth so that has tended to be the common use case. It's a bit less common (so far) that people are using Zod purely on the client side with no control over the service they're talking to, but if you have that use case, it's probably something that could be made by looking at one of the existing zod->openapi tools and working backwards!

Let us know either here or on Discord if you run into any issues getting it working, we're happy to help grow the ecosystem and this seems like a good missing piece.

**Comment by gius** [comment]
There is a small library https://github.com/josejulio/openapi2typescript/tree/main/packages/cli that is able to generate a schema from Swagger!

**Comment by akinnee** [comment]
+1

**Comment by schowdhuri** [comment]
This appears to do the job: https://github.com/astahmer/typed-openapi
