### ISSUE TITLE
Allow specific properties to be `.required`

### ISSUE THREAD

**Issue by SrBrahma** [colinhacks/zod#1176]
I have a mySchema with ~10 properties.

In my API, I use `mySchema.partial()` as all props are optional, BUT one.

I wish I could simply `mySchema.partial().required({ myRequired: true })`, as partial allows.

It would be a better solution than .partial({ 9 props }) or merging with the mySchema.shape.myRequired.

**Comment by ivosabev** [comment]
+1 fo this, it is very common scenario. 

For example I have a `orderSchema` and I have an `updateOrder()` function that takes `orderSchema.partial()`, but I want the `orderSchema.shape.id` property to be required, so I would like to do `orderSchema.partial().required({id:true})` instead of the hack I am currently using `orderSchema.partial().omit({id:true}).extend({id: orderIdSchema})`

**Comment by Antman261** [comment]
+1 -- would like this so zod can mirror the TypeScript `Required` utility type https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype

**Comment by YannBcf** [comment]
+1, I also needed this feature, thanks for your workaround @ivosabev

**Comment by SrBrahma** [comment]
Just implemented it in #1315.

Can you please take a look, @colinhacks?

**Comment by SrBrahma** [comment]
Up

**Comment by SrBrahma** [comment]
Merged in #1315
