### ISSUE TITLE
Data transformation with zod schema

### ISSUE THREAD

**Issue by asherccohen** [colinhacks/zod#1189]
Hi, I'm investigating ways to automate data transformation.

Since zod's main purpose is to validate data using a schema, would there be interest in also transforming a source object into the result described by the schema?

Probably an example would help understanding the use case.

```// Source data coming from an API.
const source = {
  foo: 'baz',
  bar: ['bar', 'foo'],
  baz: {
    qux: 'bazqux'
  }
};
const schema = {
  foo: 'foo', // Simple Projection
  bazqux: 'baz.qux' // Grab a value from a deep path
};

morphism(schema, source);
//=> { foo: 'baz', bazqux: 'bazqux' }```



This is inspired by a package called morphism: https://github.com/nobrainr/morphism

**Comment by scotttrinh** [comment]
That's a nice compact syntax, but this is something that is already achievable with `transform` which can be pretty powerful with destructuring and can do quite a bit more than just mapping:

```ts
const schema = z
  .object({
    foo: z.string(),
    bar: z.array(z.string()),
    baz: z.object({
      qux: z.string(),
    }),
  })
  .transform(({ foo, baz: { qux: bazqux } }) => ({
    foo,
    bazqux,
  }));
```

Would be cool to make it easier to use morphism with Zod, though rather than combining them since they really cover different use cases. If you have any ideas around that, feel free to reach out here or on the Discord!

**Comment by asherccohen** [comment]
That's a great explanation, thanks.
I was under the impression that .transform only affected the types, but now I see how it can map too.
I'll experiment a bit (I'm new to both libs) and then reach out with my discovering.

Kind Regards
Asher
________________________________
