### ISSUE TITLE
infer is not a function

### ISSUE THREAD

**Issue by 7flash** [colinhacks/zod#1226]
![image](https://user-images.githubusercontent.com/4569866/175771246-d2229e67-a3fa-4494-8e72-86543b1f5d91.png)

![image](https://user-images.githubusercontent.com/4569866/175771235-1807a5bf-754c-4e9e-982b-fb8e7b2c56d0.png)

![image](https://user-images.githubusercontent.com/4569866/175771216-de0adedc-f849-45e1-a92e-cf3d603ac58b.png)

**Comment by 7flash** [comment]
```
import { z } from 'zod';
```

gives the same error..

**Comment by 7flash** [comment]
![image](https://user-images.githubusercontent.com/4569866/175771301-310e2540-028e-46ac-9106-db2c212e1c2b.png)

**Comment by 7flash** [comment]
using in browser.. in vite vanilla boilerplate project..

**Comment by WilliamVearrier** [comment]
The error shows what the issue is `z.infer is not a function`

`z.infer` is not an exported function, it is a type. After typescript transpiles to plain javascript, there is no value for `z.infer`

```ts
// @ts-ignore
console.log('z.infer value:', z.infer) // z.infer value: undefined
```

Note the `@ts-ignore`. You should have received some form of error from typescript since you are referencing a type as a value. Check your `tsconfig.json` against the [requirements](https://github.com/colinhacks/zod#requirements) as there is probably some funny business in your config.
 * It might be worth doing a clean `tsc --init` in a separate directory and comparing the config with yours

Secondly, `z.infer` is essentially defined as
```ts
type infer<T extends ZodType<any, any, any>> = T["_output"]
```
Calling with `string` wouldn't be a legitimate type input and should result in an error: `Type 'string' does not satisfy the constraint 'ZodType<any, any, any>'.`

Will need to call `z.infer` with a valid `ZodType`.

I recommend looking at the documentation and specifically the [Strings](https://github.com/colinhacks/zod#strings) examples in the readme.

From your example, you'd basically end up with
```ts
const value = z.string();
type Value = z.infer<typeof value>;
...
const second = value.parse('');
```

**Comment by 7flash** [comment]
Got it.. infer output should be assigned to type not variable.. 

In my case I want to ensure that generic function accepts always variables of the same type..

![image](https://user-images.githubusercontent.com/4569866/175868998-b4df8b55-9ac9-47b3-b3f6-91bd6d6677b9.png)

Does that make sense..

**Comment by 7flash** [comment]
Alternatively I can zod.. to avoid passing the type when using my function.. does that make sense..

![image](https://user-images.githubusercontent.com/4569866/175952840-797bd320-5e48-444d-9c62-4bcbfd372a33.png)
