### ISSUE TITLE
Feature request for reverse transform

### ISSUE THREAD

**Issue by Haaxor1689** [colinhacks/zod#1237]
I love how the `.transform` function works and how it all makes working with external data so easy. In my example I'm loading and parsing an ini file and then transform it into usable JSON to work with in forms in my app. This is all great and smooth but the problem I encountered was when I wanted to save the modified data back into an ini file. What I had to do was basically double all my schemas, one for parsing data from the ini (`MatrixValueSchema`) and one for parsing my form values back to the shape of the ini file data (`RawMatrixValueSchema`).

Here is the [schema file](https://github.com/Haaxor1689/FightKnightEdit/blob/master/src/utils/types.ts#L13) for full context.

One solution that I think would work nicely, would be to add an optional reverse callback to the `.transform` helper and then a new `.reverseParse` function which would take a output value and return a input value.

I'm sure there are a bunch of more steps to think through for this to work, but I'd like to hear your opinion on usefulness of feature like this or some way to better solve this problem with current features.

**Comment by BowTiedAztec** [comment]
I have a very similar case. I'm using zod to parse data I receive from an api, transform it, and then store it in a db using prisma.

On the way in, I can use a schema like this, no problem:
```
z.object({...}.transform({...}
```

The problem is reading that data from the db later. If I try to call `schema.parse` on it, it will fail because the data matches the _output_ schema as opposed to the _input_ schema.

Because it's a JSON column in the db, I'd really prefer to use `schema.parse` instead of just typecasting so I can get the runtime safety.

The obvious workaround for now is to track the input and output schemas separately. But then I'm effectively duplicating code between the transform and output schema. Not the end of the world, but not ideal.

I think I'm basically asking to replicate the whole z.input / z.output / z.infer paradigm, either at parse time or at schema construction time.

Thank you for your consideration and the wonderful library!
