### ISSUE TITLE
special case: union types with omit and extended schema throws TS error

### ISSUE THREAD

**Issue by DanielRuf** [colinhacks/zod#1356]
We have the following case:

a base type:

![image](https://user-images.githubusercontent.com/827205/186662736-d5c13df1-355f-45e2-b33e-c9c0a07c7d24.png)

multiple extended types, one of them omits the `background_variant` field:

![image](https://user-images.githubusercontent.com/827205/186662838-d242d7d9-781d-42e0-8cab-f67bb038f265.png)

one union type for all of them:

![image](https://user-images.githubusercontent.com/827205/186663054-f5f62660-4654-4d3f-a30c-a454b728d871.png)

usage of some fields:

![image](https://user-images.githubusercontent.com/827205/186663267-e7cc0a03-e083-45ff-ba47-a58ec6851911.png)

Which results in this error:

```
error TS2339: Property 'background_variant' does not exist on type '{ type: ESuluContentBlockTypes.TEXT; settings: { hidden: boolean; schedules_enabled: boolean; schedules: ({ type: ESuluSettingsScheduleTypes.FIXED; start: string; end: string; } | { ...; })[]; } | {} | string[]; background_variant: ESuluContentBlockBackgroundVariants | null; title: string; description: string; } | ....'.
```

What is the correct approach to resolve this?

**Comment by scotttrinh** [comment]
That type error is true though since you're omitting that field on line 76? TypeScript doesn't allow you to destructure a property that isn't defined on a type, so you'll need to narrow the type down to those that do contain that property, or use `extend({ background_variant: z.undefined() })` instead if you want it to be defined but defined as undefined (which I personally do not like, but 🤷 )

**Comment by DanielRuf** [comment]
We have "resolved" it via `@ts-ignore`, because we can not split the type in our use-case.
