### ISSUE TITLE
Type inference doesn't work when spreading shapes

### ISSUE THREAD

**Issue by ChambreNoire** [colinhacks/zod#1705]
Hello,

I frequently deal with schemas like this :

    {
        enabled: false
    } | {
        enalbed: true;
        // a whole bunch of stuff in here
    }

so I wrote a little utility function :

    const withEnabled = <T extends ZodRawShape>(shape?: T) =>
        z.union([
            z.object({
                enabled: z.literal(false),
            }),
            z.object({
                enabled: z.literal(true),
                ...shape,
            }),
        ]);

However when I infer the type of a schema which includes properties defined using this 

    const MySchema = z.object({
        filters: withEnabled({
            something: z.string()
        })
    })
    type MySchema = z.infer<typeof MySchema>

The added shape is not taken into account. Here I see only the enabled true|false

I'm obviously missing something, but what ?

Many Thanks!

**Comment by santosmarco-caribou** [comment]
Hey, @ChambreNoire — the problem here is that you are spreading a possibly undefined shape.

```ts
const withEnabled = <T extends ZodRawShape>(shape?: T) =>
//                                               ^
```

If you need `shape` to be optional, you can easily solve this issue by adding a default value to it and removing the `?` mark:

```ts
const withEnabled = <T extends z.ZodRawShape>(shape = {} as T) =>
```

<img width="718" alt="Screenshot 2022-12-16 at 3 22 16 AM" src="https://user-images.githubusercontent.com/98408205/208035550-4d226aab-2e0e-49ba-a03e-eec7b103dd38.png">

**Comment by ChambreNoire** [comment]
Thanks!

That works fine as long as I pass a shape. Otherwise I get the following:

    const Schema = withEnabled()
    type Schema = z.infer<typeof Schema>;
    //     ^ type Schema = { enabled?: false; } | { [x: string]: any; }

Any ideas ?

Cheers

**Comment by santosmarco-caribou** [comment]
Try to default the generic to `{}`.

```ts
<T extends z.ZodRawShape = {}>
```

I'm on mobile right now, but I think that should work. The problem is that when you don't pass a shape it infers `z.ZodRawShape` because there's no default there. But if you set a default, it should infer `{}`, which should probably get merged with whatever you have in the union.

**Comment by santosmarco-caribou** [comment]
@ChambreNoire can we close this or are you still facing issues?

**Comment by ChambreNoire** [comment]
@santosmarco-caribou Ooops! Sorry, I totally forgot to get back you about this. Mea maxima culpa.

Yes, this did the trick. Code works fine now and is consequently way less verbose/repetitive.

Many thanks!
