### ISSUE TITLE
ZodType not working as expected with branded schemas

### ISSUE THREAD

**Issue by bram-l** [colinhacks/zod#1740]
When passing a branded string to the `ZodType` generic, the type being returned is more strict than the original schema.

For example:

```ts
const SomeBrandedString = z.string().brand<"some-brand">();

type SomeBrandedString = z.infer<typeof SomeBrandedString>;

const test: z.ZodType<SomeBrandedString> = SomeBrandedString;
```

Would give the following error:

```
Type 'ZodBranded<ZodString, "some-brand">' is not assignable to type 'ZodType<string & BRAND<"some-brand">, ZodTypeDef, string & BRAND<"some-brand">>'.
  Types of property '_input' are incompatible.
    Type 'string' is not assignable to type 'string & BRAND<"some-brand">'.
      Type 'string' is not assignable to type 'BRAND<"some-brand">'.ts(2322)
```

Zod v3.20.2

**Comment by santosmarco-caribou** [comment]
This is expected and not a bug.

`SomeBrandedString` has the following `Output`/`Input` pair:

<img width="418" alt="Screenshot 2022-12-24 at 2 44 15 AM" src="https://user-images.githubusercontent.com/98408205/209423203-3e94fba3-071a-41bb-b548-8dad56c12870.png">

However, `z.ZodType<SomeBrandedString>` will, by default, set the `Input` type parameter to `SomeBrandedString` (because that's what you have set the `Output` to be, and `Input = Output` unless you explicitly type the `Input`).

<img width="781" alt="Screenshot 2022-12-24 at 2 46 26 AM" src="https://user-images.githubusercontent.com/98408205/209423249-c87e70e7-039d-4b08-8f7e-ae1a606cb644.png">

To correctly type `test` in your example you have to set both `Output` _and_ `Input`:

<img width="520" alt="Screenshot 2022-12-24 at 2 48 42 AM" src="https://user-images.githubusercontent.com/98408205/209423319-95dbd10e-8dab-4141-9b82-4bf5ef04e68b.png">

/\ No errors.

---

Side note: this is known, expected and intended because branded types can't have the `Input` also branded. Otherwise, it wouldn't fit anything.

**Comment by JacobWeisenburger** [comment]
@bram-l,
Is the above explanation satisfactory? Or do you have any questions?

I'd like to close this issue if there are no further questions.

**Comment by bram-l** [comment]
Thanks for clarifying, makes sense!

**Comment by aphex** [comment]
Hey @santosmarco-caribou wanted to revisit what you have mentioned here as I ran into this problem trying to validate tRPC inputs.  

You can see my tRPC issue here https://github.com/trpc/trpc/issues/3602#issuecomment-1379539304 with my example repo here https://github.com/aphex/branded-trpc

After Katt's reply I realized this also was valid in zod
```ts
import { z } from 'zod'

const branded = z.string().brand('branded')
type Branded = z.infer<typeof branded>

const r = branded.parse('test')
console.log(r)
```

So it seems that zod simply does not (can not?) validate branded string on the way in, it confirms it's any string and then types the output. You mentioned _"Side note: this is known, expected and intended because branded types can't have the Input also branded. Otherwise, it wouldn't fit anything."_

With that I started to realize, and please correct me if I am wrong, but branding is a typescript only concept. Branded strings are still simply just strings that are typed on the way out to be "branded". 

So the conversation I was hoping to have here is how could tRPC help keep end to end type safety for branded strings. Currently it uses `_input` and `_output` to infer procedure parameters. Maybe it needs to have a special case for branded string type inference? When it detects a branded string it needs to use the `output` instead of the `input` to create procedure param type defs?

Any insight would be very helpful, I have gone all in on branded strings for a tRPC api and would love to find a way to keep things straight between the client and the server.

**Comment by aphex** [comment]
@KATT agree with you on the usage. That is exactly what we are doing in our codebase now with tRPC. We create ZodTypes and infer Typescript types from them. Share the TS types to the frontend and expect the frontend to pass branded strings to the query/mutation using `as`

However, of course, right now the branded string is not enforced. It is ok with any string. Just so I understand if we follow the path you are on in the playground, runtime checking would still allow any string it would just be typescript that could now detect branded issues right?
