### ISSUE TITLE
Interaction between zod and TypeScript handling of .catchall

### ISSUE THREAD

**Issue by ebroder** [colinhacks/zod#1949]
zod seems to handle `.catchall` on an object differently than the corresponding TypeScript type it generates. Given the following schema:

```typescript
const schema = z.object({
  foo: z.string(),
})
  .catchall(z.number());
```

zod will happily validate it:

```typescript
schema.parse({ foo: 'hi', bar: 0 });

// ✅ no error
```

However, if you look at the corresponding inferred type:

```typescript
type Schema = z.infer<typeof schema>;

// type Schema = {
//   [x: string]: number;
//   foo: string
// }
```

that type seems unsatisfiable directly in TypeScript:

```typescript
const x: Schema = { foo: 'hi', bar: 0 };

// Type '{ foo: string; bar: number; }' is not assignable to type '{ [x: string]: number; foo: string; }'.
//   Property 'foo' is incompatible with index signature.
//     Type 'string' is not assignable to type 'number'.
```

I'm not entirely sure what the right behavior here is - should `catchall` require that all values on the shape be assignable to the catchall type? Is there some other way to declare what the output type is? (Is there some way to declare a constant of type `Schema` that TypeScript is happy with?)

**Comment by colinhacks** [comment]
Yeah :( This actually stems from a misconception I had about TS index types at the time. It isn't actually "catchall" because all the defined keys still need to 

In fact, the fact that Zod is able to generate a type signature like this is kinda surprising since it isn't valid 

```ts
type Schema = {
  [x: string]: number;
  foo: string
}
```

> require that all values on the shape be assignable

It should, but this is kinda tricky to do. It gets more complicated if you try to incorporate the fallback schema into the type signature of `.extend`, in order to prevent unassignable keys. Thus far, this has always seemed like more trouble than it's worth to me, though it is a weird edge case.

**Comment by ebroder** [comment]
Oh yeesh. Yeah `.extend` makes this tricky.

For the record, I wanted to flag this in case there was clarity on what the correct behavior is, in which case I might take a stab at implementing it, but I haven't actually run into this issue in practice - I was doing some meta-programming on schemas and ran into this when I was writing edge case tests.

I might poke around and see I can figure out how to add that validation, but it's not a blocker for me right now.
