### ISSUE TITLE
RFC: Mocking

### ISSUE THREAD

**Issue by colinhacks** [colinhacks/zod#197]
I'm open to a PR for a `.mock` method that lets you generate mock data for your schemas.

### New base method: `.mock`
A `.mock` method on the base class. 

```ts
z.string().mock(); // => "AkvoFxGfoHFhdfKF" (random string)
z.number().mock(); // => 18916.19016 (random number)
```

### Overrides

This method could accept some parameters that let you overriding the default mocking functions for each data type (e.g. strings, numbers, tuples, etc).

```ts
z.string().mock({
  stringMocker: ()=>['hello', 'goodbye'][Math.round(Math.random())]
});
// => randomly chooses "hello" or "goodbye"
```

### Instance-specific mocking functions

There would also need to be a way to override the mocking function for a particular schema instance (probably a `.mocker()` or `.setMocker()` method on the base class). 

```ts
z.string()
  .refine(val => val === val.toLowerCase())
  .mocker(()=>{
    return randomString().toLowerCase();
  })
  .mock(); // => "akvofxgfohfhdfkf"
```

#### Refinements

Zod has no way of generating a value that satisfies a given refinement. There would also need to be a way to override the mocking function for a particular schema instance (probably a `.mocker()` or `.setMocker()` method on the base class). 

#### Unions

Which union "option" should be used to generate the value? Perhaps a randomly chosen one? Should the mocked value for an optional value be `undefined` 50% of the time?

#### Transformers

Should Zod mock a value for the input or the output type? Not a huge issue, this can just be an option/flag in the `.mock` method.

**Comment by lo1tuma** [comment]
My thoughts on this topic:

* Since `zod` is already quite big in terms of bundle-size without support for tree-shaking, I think this should be a separate package or at least a separate file that is not loaded when doing `import * as z from 'zod'`.
* I prefer static data over random dynamic data in order to implement reproducible tests. My go-to library here is [`cooky-cutter`](https://github.com/skovy/cooky-cutter) which allows you to define factories where you can partially override the default values. This makes it easy to write small test that focus only on some specific properties of an object. Maybe it would be possible to automatically create such factories from a zod schema.

**Comment by vriad** [comment]
I'm inclined to disagree. This would add maybe a kilobyte to the bundle size max. Plus I consider mocking is a pretty fundamental bit of functionality for a library that is trying to be the single-source of truth for type information.

Pretty sure we could eliminate more than a kilobyte from the bundle by using the `removeComments` option in tsc...just realized I haven't enabled that 😬

**Comment by o-alexandrov** [comment]
Based on the same building/bundling-related reasons from https://github.com/colinhacks/zod/issues/264#issuecomment-741576249
Please kindly consider to add this feature as a separate utility function
