### ISSUE TITLE
Can there be better typescript inference for z.string().startsWith and endsWith?

### ISSUE THREAD

**Issue by nasserakhter** [colinhacks/zod#1998]
When using z.string().startsWith() or endsWith() the typescript inferred type is simply string. Can there instead be a way to convert strings that have startsWith or endsWith declarations to typescript interpolated literals?

If not, is there any way to control what typescript type zod will infer to?

![image](https://user-images.githubusercontent.com/49543791/217133560-e2c027bd-12ee-4543-aacb-7044e57f4df9.png)

**Comment by JacobWeisenburger** [comment]
currently the best way I can think of is this:
```ts
const schema = z.string()
    .startsWith( 'text' ) as z.ZodType<`text${ string }`, z.ZodTypeDef, string>
type Data = z.infer<typeof schema>
// type Data = `text${string}`
```

**Comment by colinhacks** [comment]
Currently the inferred type of a `ZodString` instance is always `string`. That's not likely to change, since it requires adding generic types onto the `ZodString` class which will make the Intellisense definition of simple schemas a lot less readable, which I don't want to do. Eventually Zod will have an API for defining template literal types which will support this behavior.

**Comment by nasserakhter** [comment]
Is there anyway to custom set the inferred zod type? Like a better way than having to create a new interface which implements the zod inferred type?

**Comment by nasserakhter** [comment]
okay, I see. Thanks!
