### ISSUE TITLE
Suggestion: Alternate name alias for .catch()

### ISSUE THREAD

**Issue by icopp** [colinhacks/zod#2128]
For those of us using strict linting, `.catch()` on anything means a promise catch clause... except for when it comes to `zod`. This can result in a lot of false-positive linting results.

It would be useful if there was also an unambiguously non-promise-related alternate name to use for this method, like `.fallbackValue()`.

**Comment by colinhacks** [comment]
Hm. I'm very hesistant to add aliases because a lot of people rely on auto-completion to learn Zod, and things like this muddy the waters. I'm also confused about how a linter is throwing errors based on the existence of a `.catch()` method - not to be dismissive, but that's a bug in the linter imho.

**Comment by JacobWeisenburger** [comment]
Sorry @icopp, but I completely agree with @colinhacks on this one.

**Comment by JacobWeisenburger** [comment]
@icopp, I'm going to close this issue. Feel free to reopen if you have more to say.
