### ISSUE TITLE
zod z.string().emoji() does not throw error for numbers 

### ISSUE THREAD

**Issue by Rehan-shah** [colinhacks/zod#2228]
does not throw errors for numbers 
https://codesandbox.io/p/sandbox/adoring-boyd-vj7ikr?welcome=true

**Comment by pn320** [comment]
Hey, I'm working on this issue, I've added a test to replicate the issue, and the bit I'm trying to figure out is how to alter the regex zod uses internally for emoji validation.
In the code in `src/types.ts:556` where `emojiRegex` is declared I'm not able to find the declarations for `Extended_Pictographic` or `Emoji_Component`.
Could you point me in the right direction?

**Comment by JacobWeisenburger** [comment]
Honestly, I have no idea where they came from. I'm not super good with regex, so I'm not really the person to ask. Sorry.

**Comment by pn320** [comment]
Right, so I've done some reading. It turns out that the numbers are actually considered valid emoji characters by the unicode standard, since they can be combined with other unicode points to form the number emoji's like this 🔢, so it's not really a bug.
There is a workaround where we could include a negation for numbers in the emoji regex, but then we're sort of drifting from the unicode standard. Not sure if modifying the regex is the right way to go. Perhaps a note in the docs to make sure this doesn't catch people out?

**Comment by JamesTheTerry** [comment]
I think there is still value in having a "pictographic emoji" only string type, but I also see why deviating from unicode will make things messy.

**Comment by JamesTheTerry** [comment]
> I'll tell ya... This is one of the many reasons why I prefer to keep these kinds of built-in refinements to a minimum in Zod's core. Every single one of them has edge cases and mean different things to different use cases 😅 . There are also environment issues with where we ended up on this one 🤦 . For now, a straightforward workaround is to use `z.string.regex` with your own emoji regex.

Fair enough! But that still leaves the current emoji filter in its Unicode configuration. It could be worth calling that out within the documentation, since that's what brought us all here. 🤷‍♀️

**Comment by msobkyy** [comment]
Same issue
