### ISSUE TITLE
Zod [V2] - Transforms are not called when using .output

### ISSUE THREAD

**Issue by rossholdway** [colinhacks/zod#224]
Hi @colinhacks 

When calling `parse` / `parseAsync` on a schema that uses `.output`, the transform isn't actually run. For example:

```typescript
const name = zod.string().transform(val => val.toUpperCase());
const result = await name.parse('Ross');
```

`result` returns `ROSS` as expected, however

```typescript
const name = zod.string()
                .transform(val => val.toUpperCase())
                .output; // <--- Append .output (then later, if this were an object I can `omit()` etc);

const result = await name.parse('Ross');
```

Appending `.output` and running the above returns `Ross`. The transform isn't called. I'm running `2.0.0-beta.21`

**Comment by colinhacks** [comment]
The `.output` property is a way to access the innards of a transformer. It doesn't return a transformer. You won't be able to call `.omit()` on a transformer, since that method is only available on objects. You'll have to create a new transformer entirely if you want to modify either the input or output with something like `.omit`. 

Your code is equivalent to this: 

```ts   
const schema = z.transformer(z.string(), z.string(), val => val.toUpperCase());
schema.input; // ZodString
schema.output; // ZodString
```


You can't run .omit
