### ISSUE TITLE
z.enum typings are too restrictive

### ISSUE THREAD

**Issue by IlyaSemenov** [colinhacks/zod#2312]
This is related to #2280 but from a different perspective.

Consider a schema with a enum field which is dynamically generated with the database options (a fairly reasonable scenario in my thinking). The current typings simply don't allow this:

```ts
const options = await EnumOptionModel.query().where(...).then(map('option')) // returns string[]
const schema = z.enum(options) // Error: Argument of type 'string[]' is not assignable to parameter of type 'readonly [string, ...string[]]'
```

Granted, the list of options coming from the database could be empty. However, the author might be okay with the schema never validating in that case. Like what if they are developing a form constructor? The form will indeed never validate with no options, but under the circumstances that will be the desired behaviour. Why should Zod disallow that code?

This is happening due to:

https://github.com/colinhacks/zod/blob/51e14beeab2f469fcbf18e3df44653e1643f5487/src/types.ts#L3918

I think this is over-designed (see above why) and the whole type should be removed in favour of simple `string[]`. I realize that doing so will result in a breaking change, so I'd suggest `EnumValues` first to be set to `string[]` and marked as deprecated, then perhaps removed several releases later.

**Comment by igalklebanov** [comment]
Hey 👋 

> `z.enum` is a Zod-native way to declare a schema with a fixed set of allowable string values.
> To get autocompletion with a Zod enum, use the .enum property of your schema:
> ~ README.md

You might want to consider using `z.union` instead.

Zod enums are for string values known at compile-time, so they could provide autocompletion just like native enums would.
Allowing `string[]` is a footgun. In most cases, you should type your options into the function, instead of providing a variable.

Your example might return `[]` from the database, and the values are only known at runtime.
