### ISSUE TITLE
`flatten()` broken/useless when doing `new z.ZodError()` with a JSON stringified/parsed ZodError coming from the server

### ISSUE THREAD

**Issue by 205g0** [colinhacks/zod#2351]
A ZodError goes from server to client, hence is stringified and parsed on its way, and on the client the flatten() method is ofc gone, so I do `new z.ZodError(sentError)` which works BUT using `.flatten()` on latter yields:

```
TypeError: this.issues is not iterable
    at ZodError.flatten ...
```

Do I miss anything?

**Comment by 205g0** [comment]
here the repro: https://codesandbox.io/s/clever-mccarthy-ttsh7w?file=/src/index.ts

```ts
import { z } from "zod";

const user = z.object({
  name: z.string()
});

try {
  user.parse({ name: 1 });
} catch (e) {
  const convertBackAndForth = JSON.parse(JSON.stringify(e));
  new z.ZodError(convertBackAndForth).flatten();
}
```

**Comment by conorbrandon** [comment]
Nothing is broken here to my eye, it's just an unfortunate example of why `JSON.parse` should probably return `unknown` instead of `any`. You're performing the following steps:

1. Because a `ZodError` extends from `Error`, stringifying one will effectively stringify an object that looks like this [`{ name: "ZodError", issues: ...[], etc... }`](https://github.com/colinhacks/zod/blob/502384e56fe2b1f8173735df6c3b0d41bce04edc/src/ZodError.ts#L209)
2. Thus, what you get back after `JSON.parse` is the same thing, an object with a `name` property and an `issues` array.
3. Take a look at the `ZodError` constructor. It takes `z.ZodIssue[]` as its only parameter.
4. The problem is the parsed object is typed as `any`! So, TS is not going to complain about you passing an object, instead of just the `issues` array. 

This is what you want instead:
```ts
new z.ZodError(convertBackAndForth.issues).flatten();
```

Or, stringify the issues array and then parse that.

**Comment by 205g0** [comment]
Ok thanks.

> Take a look at the ZodError constructor. It takes z.ZodIssue[] as its only parameter.

This is nowhere documented. Would it not be more intuitive to create a new ZodError by inputting its exact shape and not just the issues prop?

**Comment by conorbrandon** [comment]
Looks like it's documented in [`ERROR_HANDLING.MD`](https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#zoderror) which admittedly is a bit hidden, but is linked on the [docs](https://zod.dev/?id=error-handling). It's also "documented" in VS Code's intellisense.

I unfortunately can't answer your second question on the design of Zod's API, I'm not an author, sorry!

**Comment by 205g0** [comment]
I checked the source and I think, I found the lines which create all the confusion:
```
  get message() {
    return JSON.stringify(this.issues, util.jsonStringifyReplacer, 2);
  }
```
`.message()` gets called when you just console.log() an JS Error (hence also the ZodError). Since its formatted like an object, I confused it as an object but it's just a string and thus, not iterable. @colinhacks  Would love to hear the motivation behind this design decision (I guees, just putting there the actual string would have been misleading too).
