### ISSUE TITLE
use .pick/.omit on ZodType

### ISSUE THREAD

**Issue by Andy-d-g** [colinhacks/zod#2403]
Hello, i'm trying to use .pick or .omit on schema which is recursive.

```typescript
type ItemAttribute = keyof Item;

type BaseItem = z.infer<typeof baseItemSchema>;

type Item = BaseItem & {
  parent_item: Item;
  subitems: Item[];
};

const baseItemSchema = z.object({
  id: z.number(),
  name: z.string(),
});

const itemSchema: z.ZodType<Item> = baseItemSchema.extend({
  parent_item: z.lazy(() => itemSchema),
  subitems: z.lazy(() => itemSchema.array()),
});

itemSchema.pick()
```

```typescript
Property 'pick' does not exist on type 'ZodLazy<ZodType<Item, ZodTypeDef, Item>>'.ts(2339)
```

I search to convert a Zodtype to a ZodObject, I don't find any informations about it.
I find that I can cast itemSchema but I lost the type when I parse some data
I don't know what try.

```typescript
const itemSchema: z.ZodObject<any, any, any, Item> = baseItemSchema.extend({
  parent_item: z.lazy(() => itemSchema),
  subitems: z.lazy(() => itemSchema.array()),
});
```

Anyone has an idea ? 

Thank you

**Comment by mattrossman** [comment]
I am facing this issue with the recursive schemas from `prisma-zod-generator`. I wish to omit certain fields from my tRPC endpoints.

After some fiddling, I learned that one way to use `z.ZodObject` is by passing it just a `RawShape` type parameter, which is the type of object passed to `z.object()` (a mapping from string key to zod schema).

Here is an example that doesn't use recursive types, but successfully labels a schema as `z.ZodObject<ThingRawShape>` with access to .omit:

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNxxwD0VcMAnmAKYDOAXHAMwB0ATAIzcALACgRAYwgA7FvBgALYFIDmAJQCGAdwDK89czgBeRCMpT1IJh2TdZUJcoAUAShFoRDAwBVFKjTr0DY08mCEw6XzUtXX0mMUkZOUjtcXkmEHV+IxRuCAAjACsmcRhHBQd-GOZXCWlZCIcUtIzea24ALRIvRiYAHhslTCYoXpCwhpUm9MyAPhnsm3yikrLIysCmGoT68snU6c42zuIAeULimF6fCuiN+eNF85XdqIDYmrEaOAAxdWAAGzELymLVyIGAMFMlGhMK+AD0APxiERfAAK6hYLCByX2GR4uAhUJhxPhSLEQA)


I don't know how to make this work recursively though. With recursive schemas, I can't define the raw shape upfront, because it needs access to the schema within.

```ts
const rawShape = {
  key: z.lazy(() => schema)  // schema is not yet defined
}
const schema: z.ZodObject<typeof rawShape> = z.object(rawShape)
```

Perhaps there is a way to infer the `RawShape` of an existing schema?

**Comment by akomm** [comment]
I can only discourage the use of `pick` and `omit`. It has a lot of limitations, including type-safety. You can pass type-check and have a runtime undefined access using it. I have a project where after I realized the problems it was the only place where constantly things broke, until I eliminated all usages of it.

The reason why pick does not exist in your case is because its API of ObjectType, but you widen the type to just Type.

Not every type has `pick

**Comment by mattrossman** [comment]
@akomm Can you explain how that addresses the issue of recursive schemas?

If I understand correctly, you're proposing that instead of using `.omit()` we create a new schema that calls individual `.shape` validators of the original schema.

However, ZodType doesn't have access to `.shape` either so I'm not sure how this helps. Here is a TS playground link where I attempt that approach on a recursive schema.

https://www.typescriptlang.org/play?ssl=14&ssc=1&pln=13&pc=3#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNxxwD0VcMAnmAKYDOAXHAMwB0ATAIzcALACgRDZnADKAYwAWTEAEMAKoyZwAvIhGVgxDixhRgAOwDmAGl1x5wADbEoTUx1kLla5gG0AuiLQxGjhnGQBXKBZgADcNFnlFJTEZCFMjaQTlDmRuAC0SLyYAHndEwoA+LRRuCAAjACsmGRgACgQbfWzuIxMLFoBKa0o7R2dXavslZHoWga1K0uVuJSgoJRn+-oCt5NT0xaUAdWAYOQgwmABJYiqcusbmtptKF9e3l+CABRxmWHoCFhyJTMfBwYgQVhwUwQeBMAAewHSqTo6gI+WIhRKmVU6kscHRhQAIkxMHiDhV8NwbCMnC43NjukDmNwaWM4NsxJygA

**Comment by akomm** [comment]
Circular dependencies are a problem. The best solution to them is that 98% of the cases you can eliminate the need for them. But for that you need to know the entire goal and context and not just have an example. My point was touching only one aspect that is clear to me here and its the general usage of pick / omit. It has a lot of problems, here one of them. If you for whatever reason have to abstract your type you will always face issues. And there are other safety problems. 

I focused on that because the title of the issue focuses on it as well: `use .pick/.omit on ZodType`

ZodType can not have .pick/.omit since .pick/.omit is something that does not make sense for all ZodTypes.

**Comment by Andy-d-g** [comment]
I try to implement an Api Helper to use on Monday. This Api use GraphQL.

You can update ressources and specify each attribute that you want obtains from the response

```typescript
// Here, I update an item and it will return only the attribute [name] and [id] of the created item
const attrs = ["name", "id"]
const createItemRequest = `change_multiple_column_values { create_item (board_id: 784) { ${attrs.join('') } } }`

// Here, I update an item and it will return only the attribute [name], [id], [items] of the created item
const attrs = ["name", "id", "items"]
const createItemRequest = `change_multiple_column_values { create_item (board_id: 784) { ${attrs.join('') } }`
```

I don't have any type on the response.

So I want to create a schema for the type `Item` and then, pick intern schema to type correctly my response base on the provided attributes

```typescript
const itemSchema = z.object({
 id: z.number(),
 name: z.string(),
 items: z.lazy(() => itemSchema)
});
```

```typescript
const responseSchema = z.object({})
for (const attr of attrs) {
 responseSchema.extend(itemSchema.pick(attr)
}
return responseSchema
```

Do you think that I can do it by an other way ?

Thx

**Comment by akomm** [comment]
I don't get. It appears you queries and the code don't fit. Why do you return just id, but define schema for an entire type. 
To me it looks like you want to return an object with an Id property. Then just define `items: z.object({id: itemSchema.shape.id})`.

**Comment by Andy-d-g** [comment]
Maybe my exemple wasn't enought clear.

You can specify for each request, the attributes that you want.

```typescript
type Item = z.inferof<typeof itemSchema>

const itemSchema = z.object({
 id z.number(),
 name: z.string(),
 description: z.string()
 items: z.lazy(() => z.array(itemSchema))
});
```

```typescript
const request = (attrs: string) => {
  let responseSchema = z.object({})
  const chunks = attrs.split(',')
  // split also { } content
  for (const chunk of chunks) {
   responseSchema = responseSchema.extend(itemSchema.pick(chunk))
  }
  return responseSchema.parse(
   axios.get(`change_multiple_column_values { create_item (board_id: 784) ${attrs} }`)
  )
}
```

```typescript
// Exemple 1
const attrs = "{ name, description }"
const response = request(attrs)
/*
{
 name: string;
 description: string;
}
*/
```

```typescript
// Exemple 2
const attrs = "{ name, id, items { id } }"
const response = request(attrs)
/*
{
 name: string;
 id: number;
 items: Pick<Item, "id">[];
}
*/
```

```typescript
// Exemple 3
const attrs = "{ items { id,  name }, description }"
const response = request(attrs)
/*
{
 description: string;
 items: Pick<Item, "id", "name">[];
}
*/
```

Thx

**Comment by akomm** [comment]
I did understand, what you want. Not sure if we talk about the same thing.

I said that recursions will always have limitations and problems, but most of the time the solution is not to use them because most of the time you do not need them and the reason is artificial. Not every recursion problem you have is solvable (in every context). Instead of giving a context as to why you even need it, you just give some code that shows why you want to use pick & omit. I feel we just circle around and getting nowhere like that. I don't see why ZodType should have pick or omit. For whatever reasons you want to solve that recursion, instead of try to eliminate the need for it.

I see a lot of question marks as to "why", but that goes the direction of support and not just some simply hint or reply. This includes questions like why you take arbitrary string to from a request to "pick" a structure that does not have arbitrary keys. That will end up in undefined reads and you won't even see that in the typing, even if you would solve or eliminate the recursion problem.

**Comment by mbsanchez01** [comment]
I'm having the same issue, there is a way to use .omit, .pick, .extend or .merge in recursive schemes?
