### ISSUE TITLE
z.string().mail() doesn't allow hyphens and dots in domain part

### ISSUE THREAD

**Issue by antonykamp** [colinhacks/zod#2632]
The validation with `z.string().email()` doesn't allow hyphens in the domain part if the domain part contains dots.
The following example throws an error:

```javascript
z.string().email().parse({ email: "antony.kamp@student.uni-potsdam.de" })
```

I found the following regex that allows dots and hyphens in the domain part of an email address:

```
  /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```
resource: https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email)
But it's not RFC compliant

**Comment by jayfz** [comment]
Hi,

I think for the example you actually meant:

```Javascript
z.string().email().parse("antony.kamp@student.uni-potsdam.de" )
```

since passing an object will throw for a different reason.

I can recreate the issue too.

**Comment by turakvlad** [comment]
We have an issue with an email that does not have hyphens in the domain part. In our case, such an email as "john@longmeadow.k12.ma.us" is not working either.

So, it looks like there is an issue with the domain part that has multiple dots in it.

**Comment by turakvlad** [comment]
Actually, I debugged it further, and it turned out that the issue is with the digits in the email address mentioned above.

For example:

```
test@subdomain.maindomain.com – works
test@subdomain99.maindomain.com – works (digits in subdomain part)
test@sub-domain.maindomain.com – works (a hyphen in the subdomain part)

test@subdomain.maindomain99.com – does not work (digits in the main domain part)
test@subdomain.main-domain.com – does not work (a hyphen in the main domain part)
```

It looks like there is some issue with the regex for the main domain part, as the subdomain part works well.

From my experience [email-validator](https://www.npmjs.com/package/email-validator) and [their regex](https://github.com/manishsaraan/email-validator/blob/master/index.js#L3) works pretty well. Maybe we can use it?

**Comment by colinhacks** [comment]
This should all work in Zod 3.22 cc @antonykamp @turakvlad

**Comment by antonykamp** [comment]
Thanks for the information 💚
