### ISSUE TITLE
PR's are going stale

### ISSUE THREAD

**Issue by rvermootenct** [colinhacks/zod#2820]
I really enjoy using ZOD, but it's pretty disconcerting to see almost 60 PR's open, and a bunch that have been closed because they have gone stale. A lot of these PR's are simple one liners that wouldn't take a long time for the maintainers to review. I see that even 5 days ago a maintainers got some work in, but there are a ton of PR's just sitting. I understand that it is a thankless job, so I do applaud you all for a great package, but confused as to why other's PR's aren't reviewed.

**Comment by JacobWeisenburger** [comment]
+1

**Comment by rvermootenct** [comment]
Also worth noting that even a message from the maintainers saying we don't want to do this goes a far way, but I'm very unlikely to add another PR after a small docs change I opened has gone stale and is almost about to be closed. [https://github.com/colinhacks/zod/pull/2485/files](This PR) is literally just updating an external link.

**Comment by JacobWeisenburger** [comment]
Fortunately for you, I can review and approve changes to the docs. So your PR is now approved and merged.

**Comment by JacobWeisenburger** [comment]
The reality is that all of us working on Zod have lives and jobs outside of Zod and so sometimes it's not our top priority. This is the unfortunate reality of free and open source software.

**Comment by rvermootenct** [comment]
@JacobWeisenburger I really appreciate it. Written words are tough because tone is often lost, please know that I was in no way trying to come across as a dick or being aggressive, just was trying to figure out what the state of the project was. Thanks for all your hard work on this package.

**Comment by colinhacks** [comment]
A few things. I'll order this from most defensive to least defensive.

- It's a teeny bit ludicrous to feel disconcerted by seeing 60 open PRs on a repo of this size and maturity. 🤷‍♂️
- Closing PRs is emotionally draining because you need to explain in detail why something isn't mergeable to avoid a defensive response from the contributor. It's also just not fun to tell someone that the work they put in won't get merged. So PRs accumulate. 
- If you sort PRs by "👍" you'll see that there are few highly-demanded, long-lived PRs. Zod is basically feature complete and the PRs that exist are quite marginal.
- I'm working on Zod 4 and a lot of things are being rewritten. Some PRs are breaking changes that can't be merged until a major version bump. Unfortunately my local `v4` branch diverged from master months ago so all changes to `master` make it marginally harder to eventually merge my v4 branch back in. This isn't a good excuse by any means, but it's important context.
- There are a lot of reasons why a PR might not be mergeable. Some address edge-casey things like discriminatedUnion, deepPartial, etc that are being rewritten or deprecated in Zod 4. Some introduce incorrect behavior (at least 3 PRs add support for ZodEffect to ZodDiscriminatedUnion which can't be done currently for subtle and annoying reasons). Some break things outright (the Deno one). Some add features I've frequently stated opposition to (`.metadata()`). Some are just too obscure (lat/long).

It's possible you're mostly referring to are small PRs that improves docs, etc. There's no excuse for not merging those sooner. I'll also try to communicate faster when a given PR is not mergeable.  

---

Can you send me the PRs that are being closed to be "going stale"? The stalebot doesn't run on PRs so no PRs are getting auto-closed. I did a scan and wasn't clear which ones you were referring to.

**Comment by rvermootenct** [comment]
@colinhacks Thank you for this really thorough response. I really appreciate it and the time you have taken to create zod. I was mostly referring to are small PRs that improves docs, etc, but I understand that I could've been more specific about that. Now that I've had some time to think I also totally agree with your first statement about the open PR's.

Thanks again for all the great work.
