### ISSUE TITLE
.keyof

### ISSUE THREAD

**Issue by carlpaten** [colinhacks/zod#286]
I have an enum mapping an external status string to an internal status string:

```typescript
enum STATUS_MAP {
  pending = internal.Pending,
  engaged = internal.Pending,
  pickup_confirmed = internal.Pending,
  canceled = internal.Cancelled,
  on_route = internal.Pending,
  on_delivery = internal.Shipped,
  delivered_recipients_here = internal.Delivered,
  delivered_recipients_not_here = internal.Delivered,
}
```

If I understand correctly there is no combinator out of the box that takes this enum and returns a schema for the keys (`pending`, `engaged`, etc.) Am I correct?

If so, I'll try to implement such a combinator and submit it as a PR this week-end.

**Comment by colinhacks** [comment]
Nope, this doesn't exist! You could add this as a `.keyof` method on ZodNativeEnum.

Ideally this would return a ZodEnum, but you'd have to make some semi-breaking changes to the ZodEnum class. Currently ZodEnum has a generic property that's a tuple of string literals (`export class ZodEnum<T extends [string, ...string[]]> extends ZodType`), but there's no real reason for that. I'd be in favor of switching to a simple `export class ZodEnum<T extends string> extends ZodType` approach which would let you implement `.keyof` methods on ZodNativeEnum and ZodObject that return a ZodEnum as expected. I can merge these breaking changes into v3.

**Comment by lilred** [comment]
That's one approach! But if I understand correctly, methods on schema objects are usually handy refinements, while this would be (conceptually, and probably implementation-wise too) a new primitive. Accordingly, I thought this would be neat as a method on the top-level object.

Here's my proposal:

1. `z.keyof(myEnum)` should infer a type equivalent to `keyof typeof myEnum`.
1. `z.keyof` should take any `Record`, or subtype thereof (worst case scenario it infers `string` or `string | number` or whatever).
1. At runtime, it behaves just like `ZodEnum`.

In an ideal world we wouldn't need this primitive, it would just be done via `z.enum(Object.keys(myEnum)`. However `Object.keys` returns not `keyof typeof myEnum` but  `string[]`. [This is because some objects have more keys than is known at compile-time.](https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208). I claim that this issue is not likely to be encountered in Zod, but if you disagree then I'm happy to table that and look for ways to only work with/support native enums.

**Comment by colinhacks** [comment]
Sounds good to me! I'm happy with this approach 👍

**Comment by hpx7** [comment]
I have a use case where I'd like to be able to do something like
```
z.keyof(z.record(...))
```
Because the keys of a record are not known at compile time, I would expect this to infer a `string` type, but provide the keyof check during parse time.

Is there a way to accomplish this with existing zod functionality? Or could this be an addition to the `z.keyof` added here?

**Comment by hpx7** [comment]
Basically this is to catch things like this:
```
{
  obj: {
    foo: 1,
    bar: 2
  },
  reference1: "foo", // this is good
  reference2: "barr" // should fail to parse since it's not a key of obj
}
```

**Comment by hpx7** [comment]
@colinhacks does my proposal and use case sound reasonable to you?

**Comment by lilred** [comment]
Have you tried implementing this using `.shape` on your record schema? It returns an object with the correct keys. You could pass it to `z.keyof` or go one further and use `Object.keys` followed by `z.enum`. Or something like that.

I liked the idea of using `z.keyof` on enums but here I think you don't actually need a new combinator, it would just be syntactic sugar. And don't get me wrong, syntactic sugar has its place, but if this isn't a blocking issue then there's no need to rush, we can have this discussion when we feel ready to.

My general concern is to avoid a proliferation of redundant combinators. If you're fine with that then one thing you could do would be to write a module for Zod extensions that re-exports everything on the Zod top-level module object. That way you can have your own syntactic sugar without waiting on any maintainers.

Hope that helps, feel free to ping back if you have more thoughts.

**Comment by hpx7** [comment]
Thanks for your reply @lilred!

I can't seem to find a `.shape` on Records, is that only available for Objects? I guess the issue here is that the record keys aren't known at compile time, so I would need some runtime function (perhaps i can use `refine` somehow?) to assert the keyof relationship I want.

**Comment by lilred** [comment]
My apologies, I wrote this first thing in the morning and it looks like I hadn't completely woken up. I looked at your example and I understand exactly what you mean. I think your best bet is a call to `refine` on the top-level object, i.e. the one that contains both the record and the key-valued fields.

I would tentatively advocate against adding a combinator addressing this particular use case to the core Zod library. The issue is that this is a kind of validation that's both non-local (the result can depend on the value of another field that can be arbitrarily far) and dynamic (the specific validity conditions aren't known until runtime). This would make it very difficult to report clear errors. It's also difficult for me to conceive of a "best" design that would cleanly address this and related use cases; the more likely result is a proliferation of special-case combinators, which is something we're trying to avoid.
