### ISSUE TITLE
Nullability discrepancy z.infer and z.ZodSchema

### ISSUE THREAD

**Issue by bjornsnoen** [colinhacks/zod#2936]
### Issue
If you infer a type from a schema that has a null filter on it, the schema won't match the inferred type. This is perhaps easiest shown rather than explained , so here is the minimal reproduction i could make.

```typescript
import { z } from "zod";

const NullableSchema = z
  .array(z.string().nullable())
  .transform((arr) => arr.filter((val): val is string => val !== null));

const func = (schema: z.ZodType<z.infer<typeof NullableSchema>>) => schema;
func(NullableSchema); // Typescript error null is not assignable to string
```

[![Edit determined-bartik-9g26qp](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/determined-bartik-9g26qp?file=%2Fsrc%2Findex.ts&embed=1)

Just by removing the `nullable()` part it works as you would expect.

### Expected behavior
The Schema should match the type `z.ZodType<z.infer<typeof Schema>>`

**Comment by santosmarco** [comment]
This is not an issue, and the code is functioning as expected.

`z.ZodType<z.infer<typeof NullableSchema>>` automatically sets both the output and input of the schema to `z.infer<typeof NullableSchema>`. `ZodType` is defined as `ZodType<Output, Def, Input = Output>`, where `Input = Output` is specified at the end.

However, `ZodTransform` alters the output of the schema from `(string | null)[]` to `string[]`. It alters the _output_ and the _output only_, meaning the input is still `(string | null)[]`, which is correct. See—you are still _accepting_ `null` as values of the array, but then filtering them out (thus changing only the schema's _output_).

To fix this, you can try the following code:

```ts
type Output = z.infer<typeof NullableSchema>;
type Input = z.input<typeof NullableSchema>;

const func = (schema: z.ZodType<Output, z.ZodTypeDef, Input>) => schema;
```

**Comment by cullylarson** [comment]
@santosmarco You're a lifesaver! Just to add another example in case it's helpful to others. I originally had this:

```ts
function changeTest<ReturnDataT extends object>(
  schema: z.ZodType<ReturnDataT>,
  data: any
): ReturnDataT {
  return schema.parse(data);
}

const schemaWithDefault = z.object({
  width: z.number().default(1920),
});

const result = changeTest(schemaWithDefault, {});

const width = result.width;
// ^? number | undefined
```

I want the type of `width` to just be `number`, not `number | undefined`.

The issue is that `.default` in the schema means that the input for this schema could have an optional `width` prop and still be valid input. However, as @santosmarco explained, only passing one argument to `ZodType` will make zod use that type for both the input and the output arguments. This makes the type of `ReturnDataT` possibly either of those arguments (the input _or_ the output); basically `type ReturnDataT = Input | Output`. And since `width` is optional in the input, it will be optional in `ReturnDataT`.

Updating the type of the `schema` argument in the `changeTest` function to this resolves it:

```ts
function changeTest<ReturnDataT extends object>(
  schema: z.ZodType<ReturnDataT, z.ZodTypeDef, any>,
  data: any
): ReturnDataT {
  return schema.parse(data);
}

const schemaWithDefault = z.object({
  width: z.number().default(1920),
});

const result = changeTest(schemaWithDefault, {});

const width = result.width;
// ^? number
```

This forces the type of `ReturnDataT` to _only_ be the type of the output, where `width` is not optional.

**Comment by colinhacks** [comment]
The original version of this now works as-is in Zod 3.23. @bjornsnoen @cullylarson
