### ISSUE TITLE
Add support for jwt

### ISSUE THREAD

**Issue by aarontravass** [colinhacks/zod#2946]
Add support to verify jwt strings. For example
```ts
const jwtSchema = zod.string().jwt()
jwtSchema.parse()
```

**Comment by abdirahmn1** [comment]
+1

**Comment by m10rten** [comment]
So a JWT: [JWT](https://jwt.io/) Is a JSON object with: Signature, Header and Payload.
To verify if it is a JWT, you can check against the headers/signature, but without a secret you wont be able to verify if the payload.

possibly this would be a nice feature:
```ts
z.string().jwt({secret: process.env.MY_JWT_SECRET}, description: "this is a users JWT"})
  .payload(z.object({...});
```

**Comment by nikelborm** [comment]
from https://datatracker.ietf.org/doc/html/rfc7519#section-2

> JWT Claims Set
>      A JSON object that contains the claims conveyed by the JWT.

Based on that, there is no real need for specifying that argument of `.payload` is `z.object`. Also I think `.withPayload` easier to read. Here is an example
```javascript
const schema = z.string()
  .jwt({
    secret: process.env.MY_JWT_SECRET, 
    description: "this is a users JWT"
  })
  .withPayload({
    sub: z.string(),
    name: z.string(),
    iat: z.number()
  });
```

**Comment by m10rten** [comment]
Agree with expire check false option, +1.

Disagree with the `.withPayload`, reason: you are already defining a .jwt, if you say: this jwt has a payload of this shape, you should just say .payload, with `.withPayload` it would feel like: "this jwt with a payload with payload in shape", when with `.payload` it would be more like:
"This is a jwt and its payload is shape."

Maybe it is a personal prefference, but I can safely say most devs prefer simple and conventions in naming, since zod is all about: .string .email .min .max .number .regex, it would not make sense to include with, instead just `.payload`.

Let me know what you think!

**Comment by aarontravass** [comment]
Agree with @m10rten 

Zod is a validation library and has nothing to do with Authorization/Authentication.

**Comment by m10rten** [comment]
> Agree with @m10rten 
> 
> Zod is a validation library and has nothing to do with Authorization/Authentication.
> 
> 

Yess, focus should be on validating a valid JWT and get data from the payload.

So plain and simple .jwt with return unknown or .payload;

**Comment by nikelborm** [comment]
@m10rten
.jwt() is still a string that consists of 3 parts divided by `.` symbol:
1. JOSE Header which is base64 encoded string of json representation of an object that has standardized structure: https://datatracker.ietf.org/doc/html/rfc7519#section-5
2. Payload which is base64 encoded string of json representation of an object that has partly standardized structure and is allowed to be extended: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1
3. signature which is either JWS (https://www.rfc-editor.org/info/rfc7515) or JWE (https://www.rfc-editor.org/info/rfc7516)

So in case you read `.string().jwt()` as `this jwt with a payload` you should really read it like `this is jwt string with JOSE Header which is base64 encoded string of json representation of an object that has standardized structure also with Payload which is base64 encoded string of json representation of an object that has partly standardized structure and is allowed to be extended and also with signature which is either JWS or JWE`

Writing `.withPayload` (meaning with payload of shape) instead of `.payload` doesn't suddenly turn zod into `Authorization/Authentication` library even in the slight degree. But `ignoreExpiration` actually does because it touches business logic of those tokens, not just DTO-logic of those tokens. There should be no `secret` even if you against turning zod into `Authorization/Authentication` library. Because signature algorithms requiring secret calculates, well, signature. And this task may be done in dozens and dozens ways. Asyncly or syncly (in terms of promises in js as thread blocking or non-blocking calculations). With dozens of libraries with some of them performing those validations using slow purely js algorithms implementations to make their code platform independent and node-version independent, some of them with inlined c, rust libraries etc, some of them with standard crypto API to take best from both worlds. Even SECRET variable is already not enough because not all tokens use sync encryption instead of async one (meaning that some of them needs SECRET as additional salt and some of them needs PUBLIC KEY which not at all secret). One part of the token such as jose header very much affects other part of jwt token such as signature in the end. That's well beyond data encoding and data structure validation and should not be considered.

And I'm not even telling you that JWTs can be validated by many libraries in JS, not only one. And if you decide to support signature validation you can't just force people to use specific library for their business validation like checking signature or checking that it was issued for specific auditory or should be used before specific date and time. Because it will force devs to use only specific set of supported encryption algorithms which is the main difference between those libraries.

`.string().jwt()` should be allowed to be called with composable functions like `.withPayload` or `.withJoseheader`. `.withJoseheader` may be used for example if user wants their jwt to accepts only specific algorithms or anything except 'none' algorithm.

Also `.string().jwt()` same as `.string().jwt().payload()` should not perform any transformations and should not return either `{joseHeader: Record<'typ'|'cty', something>, payload: Record<string, any>, signature, signature: string}` or `Record<string, any>` as underlying payload. There is `.transform` for those who wants it. I'm saying that because `.payload()` underlies that it will return only `.payload()` and this is bad design because we will have no way to get JOSE header because it will be simply stripped.

JWT by itself is not plain and simple and if you want plain and simple `.jwt()` that does only shallow validation you should reject most of the logic JWTs as tokens and leave only the logic of JWT as data-structure and leave an ability for developers to choose what business logic they want to put on top. And there is awesome tool for that in zod called `.refine()`

**Comment by m10rten** [comment]
Yess, so maybe its return type should be something like this:

```ts
interface ReturnValue<ZodAny extends z.ZodTypeAny> {
  headers: Record<HeaderTyped, string>;
  signature: {
    alg: string;
    typ: "JWT"
  };
  payload: ZodAny;
};
```

Where a `.payload` would set the schema for that payload property.
Otherwise it would be unknown.

**Comment by nikelborm** [comment]
There is no methods in zod that change the type of what was passed to them. You change the type of value from string to object.
For those who wants to change the value there is transform. It is not the responsibility of zod to transform the data. It is the responsibility of the developer who use zod.

And by the way you signature should be string and your headers should have type `{ alg: string; typ: "JWT"}`. You mistaken one for another. Typescript type for headers is also incomplete because it can have more headers than only 'alg' and 'typ'.

**Comment by m10rten** [comment]
Is it changing or validating.
You get a schema that takes in a jwt string and validates the payload.

It is not transforming if you have jwt, else why would you event implement a .jwt method?

**Comment by nikelborm** [comment]
It **DOES** transform from `string` to `object`. Your interface is not JWT. And developers will not be able to pass this jwt for further business-logic validation to any other library that handles JWTs. Because all of the libraries parse string and return their own interfaces representing this JWT. One library may want to call field `JOSE_headers` when other may decide to call it just `headers`. Object returned from those libraries **IS NOT** jwt already by RFC definition.
The task of parsing JWT is not simple either because if you look into the specifications of JWT you will find many other ways of token representation such us nested JWTs you haven't heard before. There are 2 things wrong with transforming JWT string to an object.
1. It either done by Zod, which means that all kinds of different logic to support entire JWT standard is written inside Zod and many working hours of devs are spent uselessly, when there is many more things to be done.
2. Or you connect some library as a dependency and force users to use that library and do not allow developer using `.jwt()` in zod to choose specicific library and encryption algorithm they want (because library that will be used as a dependency of zod may not support that algorithm)

**Comment by m10rten** [comment]
I believe I am following you, but is this really an issue?

Lets add an example:
```ts
import { z }  from "zod";

// both of these are on a string, check if its in a format, and then return that string.
const email = z.string().email();
// so .jwt follows the .email
const jwt = z.string().jwt();

// all you would do with a .payload is indeed a .transform with a lot of steps taken out.
const jwtWithPayloadSchema = z.string()
  .jwt()
  .payload(
    z.object({...})
  );

// so where .jwt should just check if it has these 3 elements: signature, headers and payload.
// the .payload adds a transform layer with a validation on the jwt data.
const userJwt = z.string()
  .jwt()
  .payload(
    z.object({
      userId: z.string(),
    })
  );

const parsed = userJwt.parse(unknownData);
// ^: {userId: string}, or if you want to also strip out the other parts: {signature: ..., headers: ..., payload: {userId: string}}

```

I think this way can not hurt users in their way of using a JWT.
I imagine the same for `.headers` and a `.signature` on the `.jwt` function.

**Comment by josh-i386g** [comment]
2024 and still no jwt regex :(.

**Comment by m10rten** [comment]
@colinhacks Can we get your opinion on this?

It seems jwt support would be very usefull (validating the format not the payload).

**Comment by danilomourelle** [comment]
Guys, I think validation should be on JWT format. A string, with three parts, in base64 format.... I don't think Zod should be responsable for receiving and checking signature. Also for payload, for me, it just make sense to check after I already know the string is a valid Jwt (checked by zod), and has valid signature (checked bu jose, jsonwebtoken...), then I would check payload, with another regular object schema......

I already open a PR following this line in August, should I do anything else to make it merged?

**Comment by aarontravass** [comment]
@danilomourelle Looks like you need to ping/contact @colinhacks or anyone else with merge privilege to merge your PR.

**Comment by mark-P0** [comment]
Seems like a related PR for this was merged to `v4`. Looking forward to it

**Comment by YChebotaev** [comment]
Not working for me. Gives

```
Validation error: Invalid jwt at "t"
```
<img width="730" alt="Screenshot 2025-01-09 at 22 49 12" src="https://github.com/user-attachments/assets/5fde5246-002c-412d-94f1-7d8bde5108aa" />

Token itself:
```
eyJhbGciOiJIUzI1NiJ9.eyJjb250YWN0SWQiOiJkIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiZXhwIjoxNzM4OTU0Nzk5LCJuYmYiOjE3MzYzNDYzOTF9.rxi8XZnqniLXi8W6MWi4UsTLCcHA3mOjo_hy3vvOZKk
```

**Comment by kotkoroid** [comment]
@YChebotaev It appears that your JWT is missing type claim in the protected header. If you're using [jose](https://www.npmjs.com/package/jose), you can resolve this by including `.setProtectedHeader({ alg: 'HS256', typ: 'JWT' })` when signing the token.

**Comment by scottanderson** [comment]
@kotkoroid, use of the `typ` header is OPTIONAL. The RFC specifically says that JWT implementations should ignore it, because it is for application use only.

> [5.1](https://datatracker.ietf.org/doc/html/rfc7519#section-5.1).  "typ" (Type) Header Parameter
> 
>    The "typ" (type) Header Parameter defined by [[JWS](https://datatracker.ietf.org/doc/html/rfc7519#ref-JWS)] and [[JWE](https://datatracker.ietf.org/doc/html/rfc7519#ref-JWE)] is used
>    by JWT applications to declare the media type [[IANA.MediaTypes](https://datatracker.ietf.org/doc/html/rfc7519#ref-IANA.MediaTypes)] of
>    this complete JWT.  This is intended for use by the JWT application
>    when values that are not JWTs could also be present in an application
>    data structure that can contain a JWT object; the application can use
>    this value to disambiguate among the different kinds of objects that
>    might be present.  It will typically not be used by applications when
>    it is already known that the object is a JWT.  This parameter is
>    ignored by JWT implementations; any processing of this parameter is
>    performed by the JWT application.  If present, it is RECOMMENDED that
>    its value be "JWT" to indicate that this object is a JWT.  While
>    media type names are not case sensitive, it is RECOMMENDED that "JWT"
>    always be spelled using uppercase characters for compatibility with
>    legacy implementations.  Use of this Header Parameter is OPTIONAL.

**Comment by kotkoroid** [comment]
@scottanderson Thanks for the information. However, I was dealing with the same problem as @YChebotaev and found out that Zod had trouble validating JWTs that do not contain `typ` header.

**Comment by scottanderson** [comment]
I appreciate you sharing a workaround. I was just trying to clarify that zod's behavior is indeed a bug.

I created #4350 to remove the erroneous check for a `typ` header.
