### ISSUE TITLE
cuid() considers the word corrigendum as a cuid

### ISSUE THREAD

**Issue by UdittLamba** [colinhacks/zod#3053]
![image](https://github.com/colinhacks/zod/assets/23259680/1669da9c-c904-4726-945e-50fdbd65c590)

**Comment by mass2527** [comment]
It's because the current implementation of `cuid` method is checking string using `/^c[^\s-]{8,}$/i`
1. The string must start with the letter 'c'.
2. Match at least 8 characters that are not white space or "-" until the end of the string

This happens since there's no perfect way to find only cuid from the string.

**Comment by UdittLamba** [comment]
> It's because the current implementation of `cuid` method is checking string using `/^c[^\s-]{8,}$/i`
> 
>     1. The string must start with the letter 'c'.
> 
>     2. Match at least 8 characters that are not white space or "-" until the end of the string
> 
> 
> This happens since there's no perfect way to find only cuid from the string.

For now, I am using a regex check and it seems to work so far. But would be great if this is handled better.
If I get time from work, I would like to handle this and open pr myself.
