### ISSUE TITLE
Enum error message cannot be customized

### ISSUE THREAD

**Issue by jsun969** [colinhacks/zod#3146]
According to #580 , custom error message for enum should be like this.

```ts
z.enum(['aaa', 'bbb', 'ccc'], {
  errorMap: () => ({ message: 'custom error message' })
})
```

which is counterintuitive. Though enum params also provided `required_error` and `invalid_type_error`, they are not working for custom errors.

Also, I assume `required_error` and `invalid_type_error` are the same for enum, so I hope custom error message should be like:

```ts
z.enum(['aaa', 'bbb', 'ccc'], { message: 'custom error message' })
```

**Comment by fernandollisboa** [comment]
Hey there!

I believe this issue is closely related to #3158, but I think having only a `message` attribute could be clearer and have a better chance of being accepted by the maintainers.

**Comment by colinhacks** [comment]
> Though enum params also provided required_error and invalid_type_error, they are not working for custom errors

These are working, and they're working as intended.

```ts
const TestEnum = z.enum(["value1", "value2"],
  { 
    invalid_type_error: "Invalid type",
    required_error: "Required value",
  }
);

TestEnum.safeParse(3); // Invalid type
TestEnum.safeParse(undefined); // Required value
```

The `invalid_type_error` and `required_error` options are a short-hand way to specify an error message for the two most common validation errors, so you don't need to go through the complexity of defining a custom error map. In practice it creates a new error map internally based on what you pass in and incorporates that into the error reporting system. 

Trying to parse, say, `"value3"` results in neither an `invalid_type` or `required` issue, it results in `invalid_enum_value`. Is that dumb? Probably! But ultimately these are behaving as intended for now.

Speaking of which, custom error maps are also working for me:

```ts
const TestEnum = z.enum(["value1", "value2"],
  { 
    errorMap: () => ({ message: "Custom error message" }),
  }
);

TestEnum.parse(3); // Custom error message
```

When I try to specify `errorMap` in conjunction with `required_error` or `invalid_type_error`, if gives me an informative error message indicating these can't be used together (also as expected).

> `z.enum(['aaa', 'bbb', 'ccc'], { message: 'custom error message' })`

The reason why this isn't a simple `message` API like you suggest is that there are multiple *issue types* that can originate inside this schema: `invalid_type` and `invalid_enum_value`. With a simple `message` option, that specificity would be lost, whereas a full `errorMap` does not. I think any new API should 

---

I kind of hate the `invalid_type_error` and `required_error` API since it muddies the waters for how Zod's error reporting works. So any confusion here is totally justified. But people really needed an easier way to override these kinds of error messages than specifying a full error map. I'm working on a more complete solution for Zod 4.
