### ISSUE TITLE
v3 string only allowed for enums

### ISSUE THREAD

**Issue by mmahalwy** [colinhacks/zod#338]
See:
![image](https://user-images.githubusercontent.com/3749095/111670268-df0e3980-87d4-11eb-87ce-456d3cb72de2.png)

Should be allowed to do numbers for enums

**Comment by colinhacks** [comment]
I disagree - numerical enums aren't a thing in TypeScript so they aren't supported here. 

![Screen Shot 2021-03-18 at 11 44 47 AM](https://user-images.githubusercontent.com/3084745/111672208-5b0d7f00-87df-11eb-89d1-5430ffd32c56.png)

You can still do a union of literals though:

```ts
const numericalEnum = z.union([z.literal(1), z.literal(2), z.literal(3)]);
```

**Comment by rjhilgefort** [comment]
I respect the decision to close this because TypeScript doesn't support numerical enums through the `enum` keyword, but I sorta disagree because Zod pushes folks to [Zod Enums](https://github.com/colinhacks/zod#zod-enums) which are just unions. From that perspective, I expected that I could do an "enum" of numbers and had to look through the issues to figure out how Zod wanted me to achieve what TypeScript does in fact support:

```TS
type Status = 200 | 400 | 404
```

Happy to do the `z.union([z.literal(200), ...])` approach, but consider maybe separating Zod Enums (unions of literals) more distinctly from TypeScript `enum`s or just allowing numeric literals through the `z.enum` interface.

Thanks for the great library, just wanted to toss my two cents in!
