### ISSUE TITLE
Error with `3.23.0` combined with package that uses `3.22.4`

### ISSUE THREAD

**Issue by m10rten** [colinhacks/zod#3429]
I am getting this error when using `z` from `3.23.0` with a package that is fixed on `3.22.4`:

```txt
Type 'ZodDefault<ZodNumber>' is not assignable to type 'ZodType<any, ZodTypeDef, any>'.
  The types of '_def.errorMap' are incompatible between these types.
```

When rolling back to `3.22.4` everything works again (with reloading the vscode ts-servers).

This goes for anything, not just `ZodNumber`.

**Comment by m10rten** [comment]
@colinhacks Could you look into this?

**Comment by colinhacks** [comment]
There's not a lot I can do in this case. You really don't want multiple versions floating around. The problematic package should list Zod as a peer dependency instead of forcing you to use its version.

What package is this?

**Comment by m10rten** [comment]
It's a private package, but is this then not considered breaking?

Replication is thus not possible.

**Comment by colinhacks** [comment]
All sorts of bad things happen when you have multiple versions of a package in your project, even if there are no breaking changes between the two. This kind of error would happen with any two versions of Zod, even if they're identical.

You can try this yourself. Zod 3.22.4 and 3.22.5 had literally no changes (due to an accidental patch release). 

In your package.json:

```ts
	"dependencies": {
		"zod-a": "npm:zod@^3.22.4",
		"zod-b": "npm:zod@3.22.5"
	}
```

And in a `.ts` file:

```ts
import type * as za from "zod-a";
import * as zb from "zod-b";

const schema: za.ZodType<any, any, any> = zb.string();
// Type 'Zod.ZodIssue[]' is not assignable to type 'import("/Users/colinmcd94/Documents/projects/scratch/node_modules/zod-b/lib/ZodError").ZodIssue[]'.
```

It's possible the recursive nature of `ZodIssue` is exacerbating this problem, but I'm not sure. And in any case I'm afraid I can't fix that without a far more disruptive change to the error reporting system.
