### ISSUE TITLE
feat: single method to comine `.unwrap().unwrap()`

### ISSUE THREAD

**Issue by juliusmarminge** [colinhacks/zod#3456]
Currently, if you have a schema with both optional and nullable, you have to call unwrap twice in order to get the base type. It would be nice to get it immediately.

I propose adding something like `.nonnullable()` (to match TypeScript's `NonNullable<T>` type) that does this in one shot:

Sandbox: https://stackblitz.com/edit/vitejs-vite-ursctp?file=src%2Fmain.ts

**Comment by colinhacks** [comment]
My current thinking on this is described here: https://github.com/colinhacks/zod/pull/3141#issuecomment-2036175869

If Zod ever did implemented `.nonNullable()` it would actually wrap the current schema in another `ZodNonNullable` schema, instead of unwrapping, because it needs to work in conjunction with transforms, refinements, `.or(z.undefined())`. e.g. 

```ts 
z.string().or(z.null()).refine(()=>true).transform(val => Math.random() > 0.5 ? val : undefined).nonNullable()
```
