### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ksmithut** [colinhacks/zod#347]
When importing zod as an esm module, a syntax error is thrown:

```
import z from 'zod'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

# Reproduction steps

```sh
mkdir test
cd test
echo '{"type":"module"}' > package.json
yarn add zod@3.0.0-alpha.9
echo "import z from 'zod'" > index.js
node index.js
```

```sh
$ node --version
v15.11.0
$ yarn --version
1.22.10
```

OS: Pop!_OS 20.10 x86_64 (basically Ubuntu 20.10)

# Possible fixes

I haven't pulled anything down to fix it just yet, but the thing it's complaining about is that in order for native esm modules to import other modules, you need to have `"type": "module"` in your package.json. I don't know off the top of my head what that will do to commonjs. When I tried just editing it directly in node_modules, the next issue that came up is that the imports inside of `lib/esm/` didn't have extentions, i.e. `import * as z from "./external"` instead of `import * as z from "./external.js"`.

I'll try pulling it down and document what I've tried here.

**Comment by ksmithut** [comment]
Alright, I've run across two things:

1. If I add `"type": "module"` to the package.json and change the import in my `index.js` file to `import { z } from 'zod'` instead of `import z from 'zod'`, then I get `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../zod/lib/esm/external' imported from .../zod/lib/esm/index.js`. This is because ESM in raw Node (and browsers for that matter) expect you to put the full filename in the import path including the file extension. As far as I know there isn't a way to have TypeScript fix that for you. I think that you either need some sort of process to do that for you after build or you put it in the source.

2. If I fix all of the paths to include the extension, it works for ESM but breaks for commonjs because now it's `type: module`.

You could export everything as common js instead of supporting two module systems. Another way you could handle it is possibly changing the file extensions for the esm bundles to `.mjs` so you wouldn't have to put `"type": "module"` on your `package.json`.

**Comment by beejunk** [comment]
Just ran into this issue today using v3.0.0-alpha.22 with native ES modules in Node v14.15.4.

**Comment by colinhacks** [comment]
This should be at least partially fixed with the most recent release. I switched to using Rollup to bundle the ESM module to side-step the file extension issue.

I did some tests, and you still need to add `"type": "module"` to your own `package.json`. You should always do `import { z } from 'zod'`. 

I read the Node docs thoroughly and set up Zod's package.json to support [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports). I thought this would enable you to import Zod without setting `"type": "module"` in your package.json but it didn't work for me (with Node 14, `--experimental-modules`). I guess I'm misunderstanding something. Anyway this should be largely resolved. 

@ksmithut @beejunk Give it a try with alpha.30 or later and let me know if it works.

**Comment by beejunk** [comment]
@colinhacks: Updated to alpha.30 and imports are now working. Thanks so much for getting a fix out so quick!

**Comment by colinhacks** [comment]
@beejunk Fantastic!

**Comment by ksmithut** [comment]
Fixed for me as well :) Thanks!

**Comment by colinhacks** [comment]
Fantastic! Thanks @ksmithut for the detailed issue, it was immensely helpful.
