### ISSUE TITLE
Changed behaviour of refine and merge (Failing to compile)

### ISSUE THREAD

**Issue by klima-markus** [colinhacks/zod#351]
Hi, first thank you for this library! there is a changed behaviour in v3 for merging a schema with refinement and it feels like a bug (but perhaps I have to use it in a different way^^)

So my questions are: If merging/extending a schema with refinements is not allowed, is there any other way to get this done? Or is there anything wrong with my validation? what is working is, first merging everything and than adding the refinement, but this makes it much more complex.

```
// example 1
const t0 = z.object({ temp: z.string() });
const myString = z.string().refine(val => val.length <= 255, { message: 'message' });

const t1 = z.object({ temp2: myString });
const t4 = t0.merge(t1);
const t3 = t0.extend(t1);

// example 2
const s0 = z.object({ temp1: z.string() });
const s1 = z.object({ temp2: z.string() });
const s3 = s0.refine(obj => obj.temp1.length <= 255, { message: 'message' });
const s4 = s0.merge(s3);
const s5 = s0.extend(s3);
```

v3 (latest alpha):
working:
* t0.merge(t1);

not working (not compiling):
* t0.extend(t1);
* s0.merge(s3);
* s0.extend(s3);

v1 (latest released version) + v2 (latest beta):
working:
* t0.merge(t1);
* s0.merge(s3);

not working:
* t0.extend(t1);
* s0.extend(s3);

**Comment by colinhacks** [comment]
Hey Markus!

The `.merge` method now behaves more consistently with the `.extend` method. Namely, if you merge two object schemas `A` and `B` (e.g. `A.merge(B)`), fields of `B` can overwrite fields of `A`. As a result, refinements on A may start throwing errors post-merge, for instance:

```ts
const A = z.object({ field: z.string() }).refine(val => val.field.length === 5);
const B = z.object({ field: z.number() });
const C = A.merge(B); // => ZodObject<{ field: ZodNumber }>;
// the refinement on A will throw an error
// because it expected { field: string }
// but got { field: number }
```

Part of the reason behind this change is that I wanted to get rid of ZodIntersection, since it's rarely useful and adds complexity to the parsing logic. But this issue, combined with #337, have convinced me that it has worthwhile to put it back in. You can fix your issue by changing your `.merge` calls to `.and`, which returns an intersection of A and B. This is equivalent to the old behavior of `merge`. You'll need to upgrade to the latest alpha: `yarn add zod@next`

**Comment by klima-markus** [comment]
Hey, thank you for your fast feedback. I can imagine, that something like makes everything more complicated so I'm very happy that we get it back! -> I will close this issue.
