### ISSUE TITLE
When properties have .default, zod infers properties as not optional even if I set .partial 

### ISSUE THREAD

**Issue by Qrymy** [colinhacks/zod#359]
## Example
![Screen Shot 2021-03-25 at 11 13 59](https://user-images.githubusercontent.com/26219456/112423576-42b8d980-8d76-11eb-98e7-a8fe6d8209d9.png)
![Screen Shot 2021-03-25 at 11 14 05](https://user-images.githubusercontent.com/26219456/112423580-44829d00-8d76-11eb-8b0e-c0619adeb3a3.png)

## Expected behavior
```typescript
export const Foo = z.object({
  bar: z.string().default(''),
})

const FooPartial = Foo.partial()

type InferredFooPartial = z.infer<typeof FooPartial> //  { bar?: string | undefined }
```

**Comment by colinhacks** [comment]
Calling `.default` returns an instance of ZodOptional. Also `.partial` tries to avoid unnecessarily nested ZodOptionals, so when you call `Foo.partial()` it doesn't bother wrapping `z.string().default('')` in yet another ZodOptional. Currently, I'd say this is the desired behavior. 

Note that, since the introduction of transformers, Zod separately infers input and output types for each schema:

```ts
const schema = z.string().default('');
type schemaInput = z.input<typeof schema>; // => string | undefined

// z.infer is equivalent to z.output
type schemaOutput = z.output<typeof schema>; // => string
type schemaOutput = z.infer<typeof schema>; // => string
```

So this will give you the type you want
```ts
type InferredFooPartial = z.input<typeof FooPartial>; // { bar?: string | undefined }
```

**Comment by Qrymy** [comment]
Thanks!
