### ISSUE TITLE
Error when transforming wrapped parser

### ISSUE THREAD

**Issue by supermacro** [colinhacks/zod#361]
A picture is worth a thousand words:

<img width="1239" alt="Screen Shot 2021-03-25 at 9 58 05 AM" src="https://user-images.githubusercontent.com/10621548/112484990-d37cbe80-8d50-11eb-939e-7be1b18db867.png">

Context: I want to take some `ZodType<T>` (which I have aliased as `Parser<T>`) and wrap it inside a `{ data: T }` parser, which I then want to destructure using `transform` to extract the actual data of type `T`.

I don't really know what I'm doing wrong, but it seems like in the simple case (line 5 in the screenshot) it just works. 

What am I doing wrong here?

Version: 3.0.0-alpha.32
TypeScript Version: 4.2.2

**Comment by colinhacks** [comment]
Using `transform` inside a generic function generally doesn't work. The `.transform` method relies on knowing the exact inferred type of the schema, so it can infer the output type of the transformation function. For instance

```ts
z.string().transform(val => val.length);
```

Here, TypeScript knows `val` is string, and can infer that the output of the transform is `number`.

But inside a generic function like `wrap`, the schema type is `any` because you could pass any Zod schema into it. 

You can achieve what you want, but you have to explicitly type the `wrap` function:

```ts
const wrap = <T extends z.ZodTypeAny>(
  inner: T
): ZodEffects<ZodObject<{ data: T }>, z.infer<T>> => {
  return z.object({ data: inner }).transform((val: any) => {
    return val.data;
  });
};

const schema = wrap(z.string());
schema.parse({ data: "asdfasdf" }); // => "asdfasdf"
```

Check out #355 for an explanation of how this works.
