### ISSUE TITLE
Misleading Error: "Property 'infer' Does Not Exist" When Using const Instead of type in Zod

### ISSUE THREAD

**Issue by Mandeep56Singh** [colinhacks/zod#3687]
I got the Typescript error:

Property 'infer' does not exist on type 'typeof import(.../node_modules/zod/lib/external)

`const CampaignForm = z.infer<typeof CampaignSchema>;`

Looking at the docs and node_modules the property is there.

The issue was using const instead of type.

Expected:
` type CampaignForm = z.infer<typeof CampaignSchema>;`

Actual:
 `const CampaignForm = z.infer<typeof CampaignSchema>`;

The error is misleading.

although i have this issue but for sake of clearity i have copy pasted from stack overflow 
here is the link
[stack overflow question on this issue](https://stackoverflow.com/questions/76111305/zod-property-infer-does-not-exist-on-type-typeof-import-node-modules-zo)

**Comment by median-dxz** [comment]
The Infer method is a **type helper** that you should only use it in a type declaration rather than a const declaration. You can regard it as a "function" in ts and it should not exist in actual js code.

**Comment by Mandeep56Singh** [comment]
@median-dxz  I know that , but the message in error is misleading , it questions your whole installation of zod. When this error occured i didn't look at  const or type because of misleading error message. I don't thing it's good experience for new commers and the error message is incorrect infer do exist but not on const.

**Comment by median-dxz** [comment]
@Mandeep56Singh 
OK, I get your point now. Sorry for misunderstanding before.
But I don't think it a "misleading" error message. Firstly, it's clearly claim that "infer" is not a property in the namespace "z". Secondly, after all, it's a typescript error that zod cannot affect how it will be displayed.

**Comment by Mandeep56Singh** [comment]
@median-dxz, sorry for the late reply. I'm not the only one encountering this problem; it's a common issue on Stack Overflow. Here's the link:
[Stack Overflow question on this issue](https://stackoverflow.com/questions/76111305/zod-property-infer-does-not-exist-on-type-typeof-import-node-modules-zo).

To be honest, I agree with you that this is a small issue and can be ignored. However, my point is that the error message should accurately point to the error, not mislead. As the message currently states, "Zod - Property 'infer' does not exist on type 'typeof import(.../node_modules/zod/lib/external)", many developers might think that infer doesn't exist, as reflected in the votes on the Stack Overflow question.

**Comment by DanielHarris88** [comment]
I see you hit the Typescript error ‘Property ‘infer’ does not exist on type even though Zod’s docs expose the infer helper. When you replace the const with a type alias, the compiler resolves the generic, much like a [Monroe Property Lookup](https://monroecountypropertyappraiser.org) that clarifies hidden details. Changing eliminates the error and restores proper type inference. A quick glance at the Zod release notes confirms this behavior and saves you from similar pitfalls in future schema definitions.

**Comment by JacobMartin77** [comment]
Your 'Property 'infer' does not exist' error is a common pitfall caused by treating a Zod schema as a const value instead of a type alias. Think of it like probing [Putnam Property Analysis](https://putnamcountypropertyappraiser.org) you need to query the correct source layer rather than the runtime export. Changing the declaration to a type lets Typescript resolve the schema’s shape, enabling z.infer to work as intended. After that adjustment, your form validation aligns perfectly with the inferred TypeScript interface.

**Comment by VictoriaPhillips55** [comment]
I ran into the same ‘Property ‘infer’ does not exist’ TypeScript error while pulling a Zod schema into a const. Treating the schema as a [ Tell HCO Feedback ](https://tellhcocom.online)object rather than a plain constant let the compiler locate the infer helper. Changing the declaration to a type alias forces z.infer to resolve against the actual schema definition, matching the docs. Keeping it type only clears the error and retains full IntelliSense for your form code.

**Comment by danielreed113** [comment]
I see you hit the classic ‘Property ‘infer’ does not exist on type’ snag that appears when Zod’s schema is imported as a const rather than a type, which is why the IDE shows the property but the compiler complains. In my own debugging I found the https://autozonecares.online surprisingly helpful for illustrating how subtle type mismatches can cascade into runtime confusion. Switching the declaration to a type resolved the infer lookup and cleared the remaining errors. Good catch on the docs.

**Comment by xtance** [comment]
lol at these bots spamming the issue up
