### ISSUE TITLE
Why ignore undeclared object properties in v3?

### ISSUE THREAD

**Issue by JoshuaWise** [colinhacks/zod#374]
I just read that in version 3, object schemas are no longer "strict" by default. Does this mean I have to add `.strict()` to all several hundred of my schemas to migrate to version 3? And I have to remember to add `.strict()` every time I write `.object()`? It would be nice if there were a way of opting into the old behavior without having to change hundreds of lines of code.

Honestly, I think from philosophical standpoint, a validation library should always be strict by default. But maybe I'm a purest.

Regardless, thanks for the great library.

**Comment by colinhacks** [comment]
As you might expect, part of the reason was that several people were annoyed that they had to add `.nonstrict()` to all of their schemas. You can't please everyone.

Another reason is so intersections behave more consistently with TypeScript's `&` operator: https://github.com/colinhacks/zod/issues/390#issuecomment-826252945

As for opting into the old behavior, that's difficult. Zod schemas are intended to encapsulate all relevant inside the schema itself (minimizing params or global configs). There actually is a way to do this. You basically write a file that re-exports everything in `zod` and overrides the `object` function:

```ts
// newzod.ts
import { z } from 'zod';
export * from 'zod';
export const object = z.object({}).strict().extend;

// index.ts
import * as z from "./myzod";
const strictObject = z.object({
  name: z.string()
})
```

**Comment by JoshuaWise** [comment]
The `re-export` trick works for my purposes. Thanks.

**Comment by oleg-codaio** [comment]
Looks like you can also use `z.strictObject()` in place of `z.object()`. Added here: https://github.com/colinhacks/zod/commit/6dd873c1fffcfedcaca89f48c3ee470887a88a38.

**Comment by colinhacks** [comment]
Oops totally forgot I added that, thanks @oleg-codaio!
