### ISSUE TITLE
v3.24.0 breaks SvelteKit Superforms

### ISSUE THREAD

**Issue by notramo** [colinhacks/zod#3901]
Updating from `v3.23.8` to `v3.24.0` in a SvelteKit project breaks the SvelteKit Superforms library.

1. Run `bun run svelte-check` in the project before: no errors, no warnings.
2. update Zod
3. Run `bun run svelte-check` again, without modifying any project code.

```
Type 'ZodObject<{ email: ZodString; role: ZodEnum<["Admin", "Moderator"]>; }, "strip", ZodTypeAny, { email: string; role: "Admin" | "Moderator"; }, { ...; }>' is missing the following properties from type 'TSchema': params, static, [Kind] (ts)
```

Superforms is on the latest version. I'm sure Superforms can be adapted to the new Zod changes, however, it's certainly a breaking change, and despite that the Zod breaking change released as a SemVer MINOR version instead of MAJOR. It should be 4.0 instead of 3.24.0 (unless Superforms uses some undocumented features or ones that were explicitly marked as non-stable).

**Comment by colinhacks** [comment]
Apologies, I'm sure this is frustrating. But when filing an issue on an OSS project there's never a scenario where you should be using all caps. 

There were no changes in this version aside from a few additional methods added to ZodString. That *does* change the type signature of the class. This is inevitable and I don't consider it a breaking change. Unfortunately it can still break things, usually when libraries like Superforms are strongly coupled to a specific version of Zod. 

Other times, people accidentally have multiple versions of Zod in their project. You can check this with `pnpm why zod` which should list the versions of Zod in your node_modules and why they ended up there.

It's possible this could be fixed with some upstream fixes in superforms and other similar libraries, I'm doing some compatibility checks now. Feel free to pin to 3.23 until this gets resolved.

**Comment by notramo** [comment]
> Apologies, I'm sure this is frustrating. But when filing an issue on an OSS project there's never a scenario where you should be using all caps.

Sorry. I did not meant for it's usual "screaming" meaning, I used all caps to indicate that the word refers specifically to a part of a SemVer version number. I thought it's a convention when talking about SemVer, like "MUST", or "SHOULD" in RFC 2119.
From the SemVer spec:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
>     MAJOR version when you make incompatible API changes
>     MINOR version when you add functionality in a backward compatible manner
>     PATCH version when you make backward compatible bug fixes
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

I could have used quotes though (e.g. "MAJOR"), but I only thought about it now, sorry.

> Other times, people accidentally have multiple versions of Zod in their project. You can check this with pnpm why zod which should list the versions of Zod in your node_modules and why they ended up there.

Based on this, I found the source of the error, it's actually in the Bun package manager dependency resolution algorithm. I described workarounds for Bun users in https://github.com/ciscoheat/sveltekit-superforms/issues/527#issuecomment-2533231050

Thanks for the help.

**Comment by colinhacks** [comment]
Glad you resolved this! Apologies for the misunderstanding. I tend to get defensive about semver definitions, as it's a very hard problem to solve as a TypeScript maintainer. And unfortunately the errors encountered by end users are nearly always cryptic and unhelpful, like the one you experienced.
