### ISSUE TITLE
Using `default()` inside `lazy()` forces type to be optional

### ISSUE THREAD

**Issue by LaCuneta** [colinhacks/zod#417]
This seems like a bug to me, but if I'm doing something wrong I'd be glad to know what the proper way is to handle this case.  If I do: 

```
const aSchema = z.object({
  name: z.string().nullable().default(null)
})

type A = z.infer<typeof aSchema>

// and typescript says:
type A = {
    name: string | null;
}
```

That type looks right to me.  But if I need a recursive type and I do:

```
type B = {
  name: string | null
, child: B | null
}

const bSchema: z.ZodSchema<B> = z.lazy(() =>
  z.object({
    name: z.string().nullable().default(null)
  , child: bSchema.nullable()
  })
)
```

Then I get a type inference error on `bSchema`:

```
Type 'ZodLazy<ZodObject<{ name: ZodOptional<ZodNullable<ZodString>, true>; child: ZodNullable<ZodType<B, ZodTypeDef, B>>; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'ZodType<B, ZodTypeDef, B>'.
  The types of '_input.name' are incompatible between these types.
    Type 'string | null | undefined' is not assignable to type 'string | null'.
      Type 'undefined' is not assignable to type 'string | null'.ts(2322)
```

I would expect to be able to still use `default()` with a non-optional field in this way.  It appears that `name` gets the `ZodOptional` with that `true` second type parameter is getting set with `default()`, and it's cleared out when using `z.infer<>` in the first case but not with the explicit type cast.

Zod version: 3.0.0-alpha.39
TypeScript version: 4.2.3

**Comment by colinhacks** [comment]
Interesting! I hadn't considered this case before. 

You can fix your code like this:

```ts
const bSchema: z.ZodSchema<B, any, any> = z.lazy(() =>
  z.object({
    name: z.string().nullable().default(null),
    child: bSchema.nullable(),
  })
);
```

The issue here is pretty subtle but the root cause is that schemas containing defaults have different input and output types:

```ts
const schema = z.string().default('asdf');
type in = z.input<typeof schema>; // string | undefined
type in = z.output<typeof schema>; // string
# z.type is equivalent to z.output
type in = z.type<typeof schema>; // string
```

The problem arises with the casting to `z.ZodSchema<B>` because ZodSchema actually takes three generic properties: 

```ts
class ZodSchema<Output, Def = ZodTypeDef, Input = Output>{
  // ...
}
```

As you can see `Input` defaults to `Output`, but because the Input type of `z.string().nullable().default(null)` differs from the output type, TypeScript was unhappy. This is definitely a gotcha with recursive types :/
