### ISSUE TITLE
Generate new schema based on another.

### ISSUE THREAD

**Issue by eelkeh** [colinhacks/zod#471]
My situation is as follows, let's say I have schema like:

```javascript
const Base = z.object({
    userId: z.string(),
    teamId: z.string(),
    origins: z.array(z.string()).optional(),
    publishedVersionId: z.string().optional(),
    status: PublishedStatus,
    slug: z.string(),
    title: z.string(),
    goal: z.string(),
    etc.
```

I would like another schema based on `Base` where **all the properties are optional**, so basically I would like to end with:

```javascript
const BaseOptional = z.object({
    userId: z.string().optional(),
    teamId: z.string().optional(),
    origins: z.array(z.string()).optional(),
    publishedVersionId: z.string().optional(),
    status: PublishedStatus.optional(),
    slug: z.string().optional(),
    title: z.string().optional(),
    goal: z.string().optional(),
    etc.
```

Is something like this possible with maybe some introspection on `Base.shape` and `reduce`, not sure if this is doable, would love to see an example of something like this!

**Comment by alii** [comment]
Zod support `ZodObject#partial` which makes all properties optional and returns a new schema, this might be what you need!

Otherwise, if you really want to clone the schema and map through each property, the following will work. Warning: It's not pretty.

[typescriptlang.org/play](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFAxhAHYDO8AQgIYMCmcAvCgHQQARgCsO1GAAoEFOHACunKAEliALn5MowOgHMJASgA0MuDA6sQK9cj6bteoyejAd2htb6soUVgE8JNna6BvoCYDDA9KwANgbGsmBygtHADAAWHMQAahxQDJF0VhowWsGhEOEFMXEmDNFyOh5BDvGmwDDRHE0l9jWyOhAx3aUtFGj6lDT0THCC7BwA8pVR0Tz8QqLiEiYLImIwfBx0PRwMEmyctmmsYByhUJly1BwSEjHRhnBHJb76PAB8iBMslojHgAG0ANYcXyfABuMTkHAAumtvlBfJNZLIHjA5FA6EDsdi+KT3q1iVCYcj1Aj6lw3DBWHRnhBMPwAFokJYRFZwAD8cDpSLgtMRHDCvLo1UcxLQlFkaE+CAw7EQcHBAGkYXBtHBob42aZfLcjRcOOD8Okbhx8MiaZzuctpdEADwwE0cM3zS3W252rXUwHjCgTKhzTg8qrRPhgLycKTjShAA)

**Comment by colinhacks** [comment]
As Alistair said: https://github.com/colinhacks/zod#partial

**Comment by eelkeh** [comment]
`partial` was exactly what I was looking for, thanks!
