### ISSUE TITLE
Support for ISO dates ?

### ISSUE THREAD

**Issue by ThomasAribart** [colinhacks/zod#482]
Thanks for this amazing lib 🙏

I'd like to have support for ISO string dates:
```
const schema = z.string().date()
schema.parse("2021-06-02T16:23:50.048Z") // ✅ Ok
schema.parse("2021-06-02T16:23:50.048+02:00") // ✅ Ok
schema.parse("Not a date") // 🚫 Throws
```

Is it under preparation ?

**Comment by DASPRiD** [comment]
There is `z.date()` to handle that, although if you are looking into local dates and/or times, you might want to have a look into JS-Joda together with the accompanying zod integration library (shameless self-plug ;)):

https://www.npmjs.com/package/zod-joda

**Comment by Sytten** [comment]
Glad I found this issue, this is really confusing IMO. I did think that `z.date()` would parse an ISO string into a Date. Pretty sure this would be very usefull.

**Comment by scotttrinh** [comment]
For context, Zod schemas follow TypeScript for the most part. The type of an ISO date string is `string` not `date`. None of our out-of-the-box schemas do any transforming of the input data, so they expect the input data to conform to the type you're giving them. If you expect an ISO date string on the input, but want to output a `Date` object, you can use `transform` to achieve this. If you want to keep it an ISO date string, but want to ensure that it conforms to the ISO date spec, you can use a solution like the one I suggested [here](https://github.com/colinhacks/zod/issues/482#issuecomment-906848102).

I'm still open to the idea of adding a refinement to the library that does this validation without needing to make a custom refinement, since it aligns with other built-in refinements like `email`, `uuid`, etc., but I'm not aware of anyone currently working on a PR to add this. Happy to help review one if anyone finds this feature useful!

**Comment by Sytten** [comment]
I mean its a bit rough auto close

**Comment by hbkmadness** [comment]
Here is how I did it, again it is a workaround but I think straightforward.

```
export const ISO_DATE_REGEX = /\d{4}-[01]\d-[0-3]\d/;

export const hasISODate = z
  .object({
    date: z
      .string()
      .regex(ISO_DATETIME_REGEX, 'date must be a valid ISO date'),
  })
  
```

**Comment by elevesque-nexapp** [comment]
For people coming here from search engines, this feature has been added to zod in late 2022 through `z.string().datetime()`. See https://github.com/colinhacks/zod/pull/1494 and the [3.20 release notes](https://github.com/colinhacks/zod/releases/tag/v3.20) for more details.

**Comment by DASPRiD** [comment]
@elevesque-nexapp Though that only covers date-times with UTC offset. Neither dates nor times or local date-times are handled with that.

**Comment by elevesque-nexapp** [comment]
@DASPRiD You can allow UTC offsets with the `offset: true` option, though you're right that it doesn't seem to support date or time-only strings.

**Comment by elevesque-nexapp** [comment]
@DASPRiD You're right, but I think many people (myself included) will have their needs met with only datetimes with offset. Just wanted to put the information here because after reading only the issue I almost went ahead and made my own validation with `refine`, which it turns out I didn't need to do.

**Comment by ibrahimqasim-abtrace** [comment]
I think this should be revisited. I would expect the following to work

```ts
z.string().date().parse('2023-12-02') // pass
```

Alternatively, something like this:
```ts
z.string().datetime('yyyy-MM-dd').parse('2023-12-02') // pass
``

**Comment by josh-i386g** [comment]
Useful docs here about the parameters: https://zod.dev/?id=iso-datetimes

**Comment by jens-ox** [comment]
[`z.iso.date()`](https://zod.dev/api?id=iso-dates#iso-dates) just in case anyone comes across this.
