### ISSUE TITLE
Reduce library size [Question] [Enhancement]

### ISSUE THREAD

**Issue by max-mykhailenko** [colinhacks/zod#485]
At first — thank you for this awesome project.

Recently I debug my bundle and recognise that zod is almost the same as react-dom library and it's 114kb non gziped code. I use latest version of zod 3.1.0.

Used named import of all zod, but also tried something like `import { string } from 'zod'` with the same result

```
import { z } from 'zod';

export const linkShema = z.object({
  title: z.string(),
  link: z.string(),
});

```

Is it possible to remove at least unused parts of code from my bundle, because 100+ kb it's a lot.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1213198/120937581-f34c3d80-c716-11eb-990f-c51c14f7bdaa.png">

**Comment by scotttrinh** [comment]
More manageable when gzipped and/or minified:

```
$ npx -p gzip-size-cli gzip-size index.mjs --include-original
108 kB → 17.5 kB
$ npx -p js-size js-size index.mjs
┌─────────────────┬─────────┐
│ Original (gzip) │ 17.5 kB │
├─────────────────┼─────────┤
│ Minified (gzip) │ 10.3 kB │
├─────────────────┼─────────┤
│ Difference      │ 7.19 kB │
├─────────────────┼─────────┤
│ Percent         │ 58.94%  │
└─────────────────┴─────────┘
```

looking at the output, I'm not sure what else we could do: it's pretty much just the output of `tsc` here. I don't think it's common practice for TypeScript libraries to do any minifying or anything, so I think this ends up falling on you as a consumer to minimize the impact of the library on your bundle. As it is, there is little that can be shaken out of `zod`, I think, since most of the "weight" is in the parser which is the part that does all of the real work. I'm no tree-shaking expert, though, so if anyone else can weigh in (no pun intended), I'd be interested to hear a more experienced take on this!

**Comment by lo1tuma** [comment]
I agree, zod is a pretty heavy library in terms of bundle size.
Maybe I’m wrong, but I would assume that the current API is not very good for treeshaking. Currently all features are exposed as methods on your schema object, so once you load zod and create your schemas you have everything that zod offers, no matter whether you use it or not.  
A different API might help to improve treeshaking, e.g. instead of writing

```js
const myString = z.string().refine((val) => val.length <= 255, {
  message: "String can't be more than 255 characters",
});
```

we could change the API to only load `refine()` when you really need it, e.g.

```js
import { string, refine, chain } from 'zod';

const myString = chain(string(), refine((val) => val.length <= 255, {
  message: "String can't be more than 255 characters",
}));
```

So users who don’t need `refine` could potentially benefit from not importing `refine`.

**Comment by scotttrinh** [comment]
Yeah, the obvious tradeoff there is the API-style of that more functional approach. Other libraries choose that API, such as [io-ts](https://github.com/gcanti/io-ts).

My assessment is that even if you were to break it up a bit, almost every feature is one that you would need in any non-trivial application. Being able to tree-shake away something like `refine` would only buy you a few dozen gzipped bytes, and you're likely to use it soon if you don't already.

**Comment by lo1tuma** [comment]
Actually, I’m using zod in a bunch of non-trivial projects and there are quite a few features I have never needed so far. For example: `parse()`, `parseAsync()`, `safeParseAsync()`, `superRefine()`, `transform()`, Enums, Function schemas, promises,  Instanceof, recursive schemas and some of the validations (e.g. `max()`).  
I could imagine that a bundle without those features would be noticeable smaller.

**Comment by scotttrinh** [comment]
Fair point, I don't use many of those myself! Some of those things probably would get removed during tree-shaking currently, function schemas for instance. I still think the number of bytes saved wouldn't be a very impactful number considering gzip, but that's definitely a matter of personal philosophy as to what the threshold is there. Many of those features just delegate to other features (`safeParse` -> `parse` for example), but I definitely get your point. My sense is that the vast majority of the bytes in `zod` are the useful ones that everyone uses (or would use eventually) and that the actual savings over the wire is not worth making a v4 in order to maximize treeshakeability, or even to expose a different API in v3 to chase this goal.

**Comment by scotttrinh** [comment]
Here's an example of what I mean: `superRefine` is:

```ts
  superRefine = this._refinement;
```

And `refine` also uses `_refinement`, so the cost of having `superRefine` is 33 uncompressed bytes. Other methods/features you listed are likewise aliases or thin wrappers around other internal methods that are used by things that you do (or at least would be likely to) use.

**Comment by max-mykhailenko** [comment]
Maybe problem in compilation? I see it in `node_modules` code without at least classes. 

```
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var ZodTypes_1 = require("../ZodTypes");
var base_1 = require("./base");
var ZodAny = (function (_super) {
    __extends(ZodAny, _super);
    function ZodAny() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.toJSON = function () { return _this._def; };
        return _this;
    }
    ZodAny.create = function () {
        return new ZodAny({
            t: ZodTypes_1.ZodTypes.any,
        });
    };
    return ZodAny;
}(base_1.ZodType));
exports.ZodAny = ZodAny;
//# sourceMappingURL=any.js.map
```

**Comment by colinhacks** [comment]
Like @scotttrinh said, there's a lot of circular dependencies where the base class is dependent on its own subclasses. This is necessary to add convenience methods like `.and`, `.or`, `.array`, etc. So Zod is structurally incompatible with treesplitting to some extent. 

I added minification to the Rollup config which seems to have decreased the size of `index.mjs` by 50kb (50% reduction).

**Comment by max-mykhailenko** [comment]
@colinhacks wow, it's perfect result, will try to switch our build to use `mjs` file.
