### ISSUE TITLE
[Question]: Usage of exclamation marks for ZodType readonly fields

### ISSUE THREAD

**Issue by supermacro** [colinhacks/zod#513]
First of all, thank you for this amazing package 🙏 

I've been reading through your code and stumbled upon an unfamiliar syntax:

<img width="466" alt="Screen Shot 2021-07-03 at 2 55 01 PM" src="https://user-images.githubusercontent.com/10621548/124364333-d79d5f80-dc0e-11eb-95d9-a6787c45ae97.png">

What do the exclamation marks do? What is this syntax / token called?

**Comment by colinhacks** [comment]
It's the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator), it's an operator that tells TypeScript that it's same to assume that an optional/nullable value exists. For example:

```ts
const asdf: string | null | undefined = "string";
const qwer = asdf!; // type: string
```

You should only use it if you're sure that the variable will be assigned to a real value (not undefined/null). Usually TypeScript is smart enough to figure this out automatically:

```ts
const asdf: string | null | undefined = "string";
if(asdf){
  asdf; // string
}
```

But in more complicated scenarios the typechecker may not be able to figure out what's going on. 

I'm using it as a hack though. These properties (`_type`, etc) are never actually assigned to anything, they're just a convenient way to "store" the class's generic properties (e.g. `Output`, `Input`, and `Def`) so they can be easily retrieved from an instance. 

```
const mySchema = z.string();
type schemaType = typeof mySchema['_output']; // string

// much easier than this...
type schemaType = typeof mySchema extends ZodType<infer Output, any, any> ? Output : never;
```

Because I never assign a value to `_type`, etc in the ZodType constructor, TypeScript complains, because by default it makes sure you assign values to every declared property. Adding the exclamation point tell TypeScript not to worry about it.
