### ISSUE TITLE
Add a `minMax()`, `range()`, `between()`

### ISSUE THREAD

**Issue by polarathene** [colinhacks/zod#532]
When a value uses both `min()` and `max()` it can be desirable to unify the error message to express that range instead of separate messages (user may input a value that fails validation a 2nd time).

Is that a common enough validation to warrant it's own method, or is it advised to implement through a third-party utility lib ([validator.js had an `isBetween()` but removed it](https://github.com/validatorjs/validator.js/issues/330)), or as this is rather simple through a `refine()` with a custom error message?

**Comment by lilred** [comment]
The reasoning [here](https://github.com/validatorjs/validator.js/issues/330#issuecomment-65924739) is appealing to me. Instead of including it in the library perhaps it would be a good fit for example code, for example in the README. That way users can copy and tweak if they need inclusive, exclusive, half-open, etc.

**Comment by polarathene** [comment]
Fair enough. I assume this is equivalent to doing `.min(x).max(y)`, but assigning a single error. I am still new to typescript but assume I could have a single method to call against multiple input types where a string uses `s.length` prior to the range check. Perhaps `superRefine` would be better suited (albeit more verbose):

```jsx
// Custom validators
const inRange = (x: number, y: number) => (n: number) => (n >= x && n <= y)
const inRangeStr = (x: number, y: number) => (s: string) => inRange(x, y)(s.length)

// Custom errors
const errorMonthRange = { message: "Month must be a number between 1 and 12" }
const errorCSCRange   = { message: "Value should be 3 digits; 4 if American Express" }

// ...

cc_exp_month: z.number().int().refine(inRange(1, 12), errorMonthRange),
// actual schema would also confirm input is digits, or be a number type and check min(100).max(9999)
cc_csc: z.string().refine(inRangeStr(3, 4), errorCSCRange),
```

**Comment by colinhacks** [comment]
@polarathene That's a good approach, though since it involves separately defining your error message, I'm not sure it represents an improvement over this:

```ts
const monthError = { message: "Month must be a number between 1 and 12" }
z.number().int().min(1, monthError).max(12, monthError)
```
This also provides the expected `too_small` and `too_big` `ZodIssue` types without requiring `superRefine` (which admittedly is quite verbose).

> Same issue technically applies to those methods already.

This is a really good point, there's no way to define the inclusive/exclusive behavior with min/max currently. In zod@3.7 I just implemented `gt` and `lt` (for non-inclusive checks), and added aliases `max -> lte` and `min -> gte`. Good call.

**Comment by polarathene** [comment]
> I'm not sure it represents an improvement over this

Yeah, I think providing a custom message to min/max wasn't something that came to mind at the time (new to zod around the time I raised the issue).

Is zod able to somehow recognize the combination of `.min(x).max(y)` or similar to improve it's ZodIssue to one that outputs a `out_of_bounds` or similar type/code instead? Is a `range()` or similar method worth adding? Or is this something users should handle on their end?

---

The zod 3.7 additions are great, and while an implicit ZodIssue for a range error message would be neat (eg for custom error map handling), your example of the custom message to the two calls is good too, thanks! :+1:
