### ISSUE TITLE
Add .promise() to ZodType

### ISSUE THREAD

**Issue by rubber-duck-software** [colinhacks/zod#537]
z.function() is remarkably useful for writing typesafe functions. Often these functions will be async, thus the return type will be a promise. Adding a .promise() method to the base class ZodType would enable syntax like 

```js
const getUsernameById z.function
    .args(number())
    .returns(z.string().promise())
    .implement(async id => {
        ...
        return username
    })
```

This would be a bit more ergonomic for the developer frequently writing async function definitions.

**Comment by scotttrinh** [comment]
@rubber-duck-software 

How is that different from the existing `z.promise` type?

This seems to type-check just fine:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/1682194/125842431-856297cb-9315-4732-aa2a-076e0152090d.png">

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFAxhAHYDO8A5gKYwCqDrUdAhiFYAhAJ4BJYnAC8KAHSYArnWoxg9ABQBKCnF1xZfKMwbrksugpAAjHlu179Udgt4mzYHCGDdTsplGA6Zjt7PVlQMAAbVkE6GHU+BhFlOGBJKQA+RB0HPScYFzoCBW5eAVZyHN00bSA)

**Comment by rubber-duck-software** [comment]
Purely a convenience method like `.array()`. Type checking remains unchanged. 

`.array()` adds readability. Often times we say "string array" so it is convenient to type "z.string().array()"

`.promise()` would fall under a similar category. We often think of an async function as returning a string, so we might start by typing `z.string()` but then finish by typing `.promise()` since the function is async leaving us with `z.string().promise()`.

**Comment by scotttrinh** [comment]
@rubber-duck-software Thanks for the explanation. I don't have a strong opinion on this since I didn't even know about the `array` method on the various primitive types, but I definitely find "container" types to make more sense the other way: e.g. `Promise<string>`, `Array<string>`, `Set<string>`, etc, but I realize that it's somewhat stylistic.

Since it seems aligned with the existing API style, I'd be happy to review a PR that adds `promise` everywhere there is an `array` method.
