### ISSUE TITLE
Easy way to check array for duplicates

### ISSUE THREAD

**Issue by SlateDave** [colinhacks/zod#546]
Hi!

I have a feature proposal.
Namely to quickly and easily reject a ZodArray containing duplicate values.
Right now I'm doing it this way:

```
something.array().refine( ( array ) => {

    for ( const arrayItem of array ) {
        
        if ( array.filter( ( item ) => item === arrayItem ).length > 1 ) {
            return false;
        }
    }
    
    return true;
} );
```

It would be nice to have a faster way of rejecting an array with duplicate values such as ``something.array().unique()``

**Comment by colinhacks** [comment]
I like the idea of a `.unique()` method but I'm not sure this feature is worth adding into the core library. 

Here's a more performant and less verbose implementation of this refinement:

```ts
const myArray = something.array().refine((array) => {
    return new Set([...array]).size === array.length;
  });
```

Unfortunately the array that gets passed into `.refine` is a deep clone of what you passed in. Moreover, all elements of that array are also deep clones, so doing object equality comparisons (`===`) doesn't actually work. Hadn't considered this limitation before...hm. It'll work fine for primitive values though (strings, numbers, booleans).

**Comment by illarionvk** [comment]
I agree that this feature might not be worth adding to the library because the `refine()` method can cover all use cases with minimal effort.

Personally, total library size and solid types are more important to me than convenience methods.


P.S. [Joi `array.unique()` method](https://joi.dev/api/?v=17.4.1#arrayuniquecomparator-options) accepts a comparator function for flexibility. [See implementation](https://github.com/sideway/joi/blob/5f33cb61d3b29419e0724088cc87c0158fde9e51/lib/types/array.js#L472).
