### ISSUE TITLE
Catchall override shape properties on inferred typescript type

### ISSUE THREAD

**Issue by ehupin** [colinhacks/zod#575]
Hi all!

With zod v3.5.1, running the following code throw a TS2322 typescript exception:

```typescript
import { z } from "zod";

const ZodEntity = z.object({
  name: z.string(),
}).catchall(z.number())

export type Entity = z.infer<typeof ZodEntity>;

const e01: Entity = {
  name: 'my_name'
}
```

Typescript error:
```
error TS2322: Type '{ name: string; }' is not assignable to type '{ [x: string]: number; name: string; }'.
  Property 'name' is incompatible with index signature.
    Type 'string' is not assignable to type 'number'.
```

I would expect the `catchall()` function to not alter the type definition for the property `name`. Is this a bug or am I doing things wrong ?

Thanks :)

**Comment by scotttrinh** [comment]
I believe this is related to the TypeScript issue that is outlined in [this section of the TypeScript Deep Dive book](https://basarat.gitbook.io/typescript/type-system/index-signatures#excluding-certain-properties-from-the-index-signature).

![image](https://user-images.githubusercontent.com/1682194/128397954-905872e2-a182-4b72-b94f-2852fe69a8d3.png)

This is not really a Zod issue since you can see that just declaring the type manually also fails for the same reason:

```ts
export type Entity = { name: string } & { [key: string]: number };

const e01: Entity = {
  name: 'my_name'
}
```

[TypeScript Playground](https://www.typescriptlang.org/play?ts=4.3.5#code/KYDwDg9gTgLgBDAnmYcCiA7GBLJcC8cA3nBgIYC2wAXHAM4xTYYDmcAvnAGTFwDaAa2CJaDJqwC6tDAFcKAI2BQOAbgBQagMYQMDOMAAMARlqYceQkTVxSlGnADkFRAH1yVB2vZA)

**Comment by scotttrinh** [comment]
@ehupin 

Note that you can still use the schema to create these objects, and they will be properly typed, you just can't use the inferred type and manually create these objects. This actually is a good reason to use Zod if you plan on generating these types of objects since it will force TypeScript to accept this object as this type even though you couldn't normally do that.

![Screen Shot 2021-08-05 at 13 59 03](https://user-images.githubusercontent.com/1682194/128398613-62130aff-7baf-40c7-8f28-4c7c118b98d9.png)

[TypeScript Playground](https://www.typescriptlang.org/play?ts=4.3.5#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFAxhAHYDO8AWiQKJ0zAwCecAvCgB0EAEYArAKbUYACgQU4cOgEMQkgFzCmUYHQDmsgJQAaCmiNDqKmNQAWKgDaPZyIXQCuIUZKjGjVLSM8JIADACMAnCsxBxcvEJgKlAMkvKKymqacADkIDwA+qrqOeZGlEA)
