### ISSUE TITLE
Ignore entry does not respect a schema

### ISSUE THREAD

**Issue by armandabric** [colinhacks/zod#627]
Hey there,

Is there a way to filter element of an array that does not match our schema? 

For example I have this schema:

```ts
enum BarType {
  Big = "big",
  Small = "small",
}

const schema = z.object({
  foo_id: z.string(),
  bars: z.array(
    z.object({
      id: z.string(),
      type: z.nativeEnum(BarType),
    }),
  ),
});
```

Is there a way to ignore in the `bars` entries all the type that are not valid `BarType` enum? 

Here a gist with a complete example: https://gist.github.com/armandabric/f88bf690ade47d292ef3cec11716d41f

**Comment by scotttrinh** [comment]
It's going to be a _little_ verbose because allowing "fallthroughs" in parsing always forces you to deal with the fallthrough case, which I think is a good discipline to have.

I can think of two possible ways to approach this with our existing API:

## Using `preprocess`:
[CodeSandbox](https://codesandbox.io/s/xenodochial-austin-obhsb?file=/src/index.ts)

This considers the filter a part of getting the _input_ data into the correct shape.

```ts
  const schema = z.object({
    foo_id: z.string(),
    bars: z.preprocess((inputBars) => {
      const result = z.array(z.any()).parse(inputBars);
      return result.filter((bar) => barSchema.safeParse(bar).success);
    }, z.array(barSchema))
  });
```

## Using `transform`:
[CodeSandbox](https://codesandbox.io/s/vibrant-wing-p26p2?file=/src/index.ts)

This considers that the input itself could be one of two types: `Bar` or `GenericBar` and treats them both as first-class schemas, where this transform just chooses one of the union members to keep.

```ts
  const schema = z.object({
    foo_id: z.string(),
    bars: z
      .array(z.union([barSchema, genericBarSchema]))
      .transform((bars) =>
        bars.filter((bar): bar is Bar => barSchema.safeParse(bar).success)
      )
  });
```

**Comment by armandabric** [comment]
Thanks for this detailed answer. I was expecting a more complex solution! That a good point for zod.

I will go with the `preprocess` version as it does not require a generic version of the the barSchema. I also found more natural to filter the entry before the verification of the structure rather than after.

**Comment by scotttrinh** [comment]
> Theses two techniques works but they also silently reject all bars that have any validation issues (eg: the foo id is an integer instead of a string).

It doesn't seem to do that for me. I updated the CodeSandbox of the `preprocess` to check for passing a number in `foo_id` and it fails parsing as you would expect.

**Comment by armandabric** [comment]
If I run this:

```ts
 const result = fooSchema.parse({
    foo_id: "foo-1",
    bars: [
      { id: "bar-a", type: BarType.Big },
      { id: 2, type: BarType.Small },
      { id: "bar-c", type: "not-a-bar-type" },
    ],
  });
```

I got on the first entry left without any error on the `bar.id` type:

![image](https://user-images.githubusercontent.com/95120/131861769-83c3ee84-7f4d-4e06-928f-d0ac3642c70e.png)

**Comment by scotttrinh** [comment]
Ahh, you said "foo id", so I thought you meant the `foo_id` property of the base schema. You can make the input schema as strict as you want instead of using `z.any()`. I've updated on the CodeSandbox.

**Comment by armandabric** [comment]
Ho my bad! It works perfectly by replacing the `z.any()` in the preprocess. 

Thanks again
