### ISSUE TITLE
Best practices: Use schema validation along classes

### ISSUE THREAD

**Issue by X-Titouan** [colinhacks/zod#641]
Hello,

This issue is not related to a Zod problem, but I'm sure people using the lib can help me <3

This is a simple Schema (we have to imagine it is more complex):

```
export const PersonSchema = z.object({
    id: z.string(),
    firstname: z.string(),
    lastname: z.string()
});

export type PersonType = z.infer<typeof PersonSchema>;
```

On server side, when I get a POST request, I can validate the payload using:

```
const newPerson = PersonSchema.parse(payload);
```

Great, my noSQL database will stay clean !

But now, I want to use this on client-side. So I use the same method.

```
const newPerson = PersonSchema.parse(payload);
```

My front get a Person object now, but to display it, I would like to use a class method like this for example:

```
newPerson.getFullName();
```

But newPerson is not a class instance...

So far, I found those solutions:

**Solution 1:**

Create a class Person:

```
class PersonClass implements PersonType {
    id: ZodString['_output'];
    lastname: ZodString['_output'];
    firstName: ZodString['_output'];

    constructor(newPerson: PersonType) {
        this.id = newPerson.contactEmail;
        this.lastname = newPerson.lastname;
        this.firstname = newPerson.firstname;
    }

    getFullName() {
        return this.firstname + " "  + this.lastname;
    }
```

OR

```
class PersonClass implements PersonType {
    id: z.infer<typeof PersonSchema.shape.name>;
    lastname: z.infer<typeof PersonSchema.shape.name>;
    firstName: z.infer<typeof PersonSchema.shape.name>;

    constructor(newPerson: PersonType) {
        this.id = newPerson.contactEmail;
        this.lastname = newPerson.lastname;
        this.firstname = newPerson.firstname;
    }
    
    getFullName() {
        return this.firstname + " "  + this.lastname;
    }
}
```

I found this on the same subject: 

https://github.com/colinhacks/zod/issues/38

But the more Person will have attributes, the more the class size is also growing. And I will have to parse my object, then to make an instance of the class...

**Solution 2:**

I don't use classes, and I create a getFullName() methods like this:

```
const getFullName = (person: PersonType) => {return person.firstname + " " + person.lastname;}
```

So my question is:

**How and when do you use Zod in your projects ?**

Only to validate payloads ? How to use methods on parsed objects?

**Comment by scotttrinh** [comment]
Definitely a matter of taste here, but I find a functional style and using POJOs (Plain old JavaScript Objects) is more idiomatic with JavaScript than this more traditional OO style, especially since JavaScript classes are not classical-OO classes, since they're syntactic sugar over regular JS functions/prototypes. If classes aren't strictly necessary, you can attach functions directly to any plain object, also:

[CodeSandbox](https://codesandbox.io/s/gifted-haze-zri05?file=/src/index.ts)

```ts
const person = z.object({
  id: z.string(),
  firstName: z.string(),
  lastName: z.string()
});
type Person = z.infer<typeof person>;

const valid = {
  ...person.parse({
    id: "abc",
    firstName: "Scott",
    lastName: "Trinh"
  }),
  getFullName: function (this: Person) {
    return `${this.firstName} ${this.lastName}`;
  }
};
valid.getFullName(); // "Scott Trinh"
```

**Comment by X-Titouan** [comment]
Attach functions to object could work yes, but how can I attach the same function to all parsed object ?

like:

```

const person = z.object({
    id: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    getFullName: z.function().nullish().transform(function(this: Person) {
          return `${this.firstName} ${this.lastName}`;
    })
});
type Person = z.infer<typeof person>;
```

But I got an error: 

```TS2502: 'this' is referenced directly or indirectly in its own type annotation.```

**Comment by scotttrinh** [comment]
Yeah, I wouldn't think that you'd want the function itself in the schema since the schema is really just about validating data. And, as you've seen, you cannot implement the function within the schema unless you made it lazy, but then you'd end up having to write the type out manually.

I don't often write class-based code, so I don't think I'm in a great position to help you out here, so I'll let someone else chime in here. I imagine that most class based code uses validation as part of the constructor, but I don't know how you avoid having to redeclare all of the types as you've pointed out.

Another option is to use modules as a class-like structure. This is more similar to what I often do in practice and has a similar feel to class-based solutions.

[CodeSandbox](https://codesandbox.io/s/divine-dawn-19lz8?file=/src/index.ts)

```ts
// Person.ts
import { z } from "zod";

const person = z.object({
  id: z.string(),
  firstName: z.string(),
  lastName: z.string()
});
export type Person = z.infer<typeof person>;

export function create(data: unknown) {
  return {
    ...person.parse(data),
    getFullName: function (this: Person) {
      return `${this.firstName} ${this.lastName}`;
    }
  };
}
```

```ts
// index.ts
import test from "tape";
import * as Person from "./Person";

test("valid", (t) => {
  const valid = Person.create({
    id: "abc",
    firstName: "Scott",
    lastName: "Trinh"
  });

  t.equal(valid.getFullName(), "Scott Trinh");
  t.end();
});
```

**Comment by X-Titouan** [comment]
```
export function create(data: unknown) {
  return {
    ...person.parse(data),
    getFullName: function (this: Person) {
      return `${this.firstName} ${this.lastName}`;
    }
  };
}

This is a great idea ! I think I will use this "factory" to add all my "class" functions to all objects !

```

**Comment by scotttrinh** [comment]
Closing, but feel free to add any additional thoughts here. If we want this to be an ongoing discussion point, we can also migrate this to a GitHub discussion.
