### ISSUE TITLE
Alternating results when using `regex` inside an `object`

### ISSUE THREAD

**Issue by JuanM04** [colinhacks/zod#669]
Running the same schema `safeParse` method when a item is of type `regex` returns alternating results.

```ts
import { z } from 'zod'

const schema = z.object({
  number: z.string().regex(/^\d+$/g).nullish()
})

const data = {number: '123'}

console.log(
  schema.safeParse(data).success, // => true
  schema.safeParse(data).success, // => false
  schema.safeParse(data).success, // => true
  schema.safeParse(data).success, // => false
  schema.safeParse(data).success, // => true
  schema.safeParse(data).success, // => false
)
```

**Comment by colinhacks** [comment]
Fixed in 3.9.4+. Wasn't familiar with this particular "feature" of JS regexes: https://stackoverflow.com/questions/2630418/javascript-regex-returning-true-then-false-then-true-etc

In v3.9.4+ Zod now manually resets `regex.lastIndex` before each validation which solves this problem. Getting rid of `g` would work too.
