### ISSUE TITLE
Undocumented breaking change for `transformer` in 3.9.0

### ISSUE THREAD

**Issue by m-rutter** [colinhacks/zod#679]
In `3.9.0` there was a breaking change to the `.transformer` method. Previously, as is currently documented in the Zod2->Zod3 documentation `.transformer` takes a single argument, a Zod schema. `.transformer` now appears to expect 2-3 arguments and all tests relating to `.transformer` have been rewritten to avoid using the `.transformer` method (in many cases the previous test was left commented out). 

`transformer` is not a very well documented method and the project appears to be moving away from it, but nethertheless it is a documented method and 3.9.0 should have been 4.0.0 or the change to .transformer should be reverted.

I've been able to rewrite all of our current usages to work without it, but ideally this should have been communicated via semver.

**Comment by FlorianWendelborn** [comment]
What `transformer` are you referring to? I can’t find any mention of this in the 3.9 documentation. It looks like this used to be a feature in 2.x, so I’m not really sure how you’re surprised that it doesn’t exist/work the same way in 3.9.

So, if this is still possible to use somehow, then you should assume that it’s some internal, private API that you just happen to be able to call from the outside. It’s undocumented in the current version of zod and IMO should not be a breaking change as internal API changes are rarely considered in release notes due to them not being officially supported.

**Comment by m-rutter** [comment]
> What `transformer` are you referring to? I can’t find any mention of this in the 3.9 documentation. It looks like this used to be a feature in 2.x, so I’m not really sure how you’re surprised that it doesn’t exist/work the same way in 3.9.
> 
> So, if this is still possible to use somehow, then you should assume that it’s some internal, private API that you just happen to be able to call from the outside. It’s undocumented in the current version of zod and IMO should not be a breaking change as internal API changes are rarely considered in release notes due to them not being officially supported.

https://github.com/colinhacks/zod/blob/45762b52d512a053eef12aba96c7858f19820f3a/MIGRATION.md

**Comment by m-rutter** [comment]
@FlorianWendelborn My mistake, I misread the migration documentation when transitioning from Zod2->Zod3, and I started depending upon a an undocumented `.transformer` method, which is a holdover from Zod2. Closing the issue.
