### ISSUE TITLE
Can't call .pick() on object().refine()

### ISSUE THREAD

**Issue by michalkvasnicak** [colinhacks/zod#704]
In version 1.x I could have this schema:

```ts
const validator = z.object({ something: z.boolean() }).refine(v => !!v);

validator.pick({ something: true });
```

Using zod `3.9.8` I get `TypeError: validator.pick is not a function`. How can I achieve the same thing?

**Comment by scotttrinh** [comment]
@michalkvasnicak 

This is a common issue coming from v1: `transform` and `refine`/`superRefine` actually return a different type instead of the same type. That is because it's hard to reason about the value being passed to those functions if we allow arbitrary changes after.

You can achieve a similar effect by exporting a refinement function that properly types the input for whatever might need to use it downstream. I'm not sure I understand your example, but it would look like this

```ts
// module-a.ts
export const refinement = (v: { something: boolean }) => !!v; // Turns an object into a boolean?

export const schema = z.object({ something: z.boolean() });

// downstream usage:

import { schema, refinement } from "module-a";

const extended = schema.extend({ somethingElse: z.string() }).refine(refinement);
```
