### ISSUE TITLE
How to validate an enum inside a schema

### ISSUE THREAD

**Issue by alveshelio** [colinhacks/zod#755]
I'm using zod alongside react-hook-form and I need to validate when the user submits the form that the data matches my schema.

I have a plugin to generate GraphQL types, queries and mutation and it generates this enum
```
export enum Audience_Range_Enum {
  ElevenTwenty = 'ELEVEN_TWENTY',
  FiftyOneOneHundred = 'FIFTY_ONE_ONE_HUNDRED',
  None = 'NONE',
  OneHundredOnePlus = 'ONE_HUNDRED_ONE_PLUS',
  OneTen = 'ONE_TEN',
  TwentyOneFifty = 'TWENTY_ONE_FIFTY'
}
```
And when the user selects an option this is what he'll be passing. 

So I have this schema
```
const schema = z
  .object({
    teamLeadOf: z.string().optional(),
    coachOf: z.string().optional(),
  })
```

And instead of using `z.string()` I'd need to check if it's a value of `Audience_Range_Enum`. How can I check this in the schema? Is it possible?

I've checked the doc and the only examples with `z.enum()` or `z.nativeEnum()` are used outside of the schema.

Thank you

**Comment by scotttrinh** [comment]
@alveshelio 

You can use `z.nativeEnum` in this case instead of `z.string` like this:

```ts
const audienceRangeEnumSchema = z.nativeEnum(Audience_Range_Enum);

const schema = z
  .object({
    teamLeadOf: audienceRangeEnumSchema.optional(),
    coachOf: audienceRangeEnumSchema.optional(),
  });
```

I think the concept your missing is that a `ZodObject` schema is just a type that is made up of other Zod types. So the "values" of a `ZodObject` schema are just themselves other Zod schemas like `z.string()`, `z.union`, `z.nativeEnum`, etc. Does that make sense?

Closing, but feel free to ask more questions here if you need more help or clarity!

**Comment by alveshelio** [comment]
Hi @scotttrinh thank you very much for your help, much appreciated
