### ISSUE TITLE
Required is not the default, or it is not behaving as I expect it to

### ISSUE THREAD

**Issue by nemonemi** [colinhacks/zod#781]
The documentation states that all fields are required by default, however, that is not the case.

```ts
const validationSchema = z.object({
    name: z.string(),
  });
```

When tested, this schema performs the type check, but not the content check, which would be expected in order to validate if the required field is filled or not.
This results in success, although the value is an empty string: `console.log(validationSchema.safeParse({ name: '' }));`

**Comment by scotttrinh** [comment]
@nemonemi 

That is a slight misunderstanding of what we mean by "required", and that's common since people tend to use a tool like Zod in use cases like form validation where something being "required" means "not empty".

We mean in the type-level sense. `""` _is_ a string and it _is_ a value. We have a built in refinement that can ensure that the value has a minimum length: `z.string().min(1)` would do the trick, but you probably also want to do some more specific refinement with potential trimming, escaping, etc.
