### ISSUE TITLE
Object properties are all optional by default

### ISSUE THREAD

**Issue by midwesterntechnology** [colinhacks/zod#797]
`import * as Zod from "zod";`

`const Dog = Zod.object({`
`name: Zod.string(),`
`age: Zod.number(),`
`});`
`type Dog = Zod.infer<typeof Dog>;`

Copied this code straight from the docs. The type of "Dog" is { name?: string, age?: number }. In the docs it says it should be { name: string, age: number }

**Comment by scotttrinh** [comment]
@midwesterntechnology 

As the docs state, you must enable the `strict: true` setting in your `tsconfig.json` in order to get correct type inference.

**Comment by srounce** [comment]
I am also having a similar issue with `3.11.6`. I have a library package 'A' which exports a function `makeSchema` which has the signature: `<T extends ZodRawShape>(z: Zod) => Zod.ZodObject<T>`, where T is passed to a `Zod.object` call and returned. When I call `makeSchema` from within the library, the fields are all required as expected. When calling `makeSchema` from another package and passing the resultant object to `Zod.infer` all the fields in returned are optional.

**Comment by DavidR95** [comment]
In case anyone had the same issue as me (with a new Nest project, in this instance), I thought I had enabled `strict: true`, but I also had `strictNullChecks: false` set separately, which was making all properties optional. Just needed to enable that too (or remove it, as it's the default) and everything worked fine.

**Comment by scotttrinh** [comment]
@srounce 

After checking that you don't accidentally have `strictNullChecks: false` (thanks @DavidR95!) can you verify that they're using the same version of Zod and TypeScript? As you noted, `infer` is working _within_ a single package/module boundary, so it must be something about how dependencies are being resolved and/or how typescript is handling the imported type definitions.

**Comment by srounce** [comment]
I can confirm I have `strictNullChecks: true` in both projects. The library package re-exports the version of Zod that it uses so they resolve to the exact same package. Turns out it was the typescript version that the consumer project was using. Updated it and everything is now fine, thanks for your help.

**Comment by MarcelWaldvogel** [comment]
Similar case here: VSCode mouse-over was showing all fields to be optional.
- `strict` and `strictNullChecks` were both `true`
- `tsc` in the project was 4.5.2
- `tsc` that VSCode claimed it was using was also 4.5.2
- However, VSCode somehow still used what is apparently the system-installed version (4.1.3 on Ubuntu 21.10/Impish).
After `npm -g install tsc` and a VSCode restart, everything works as expected.

**Comment by kb-ig** [comment]
I'm seeing the same behavior even after checking all of the above. The problem was indeed down to my `tsconfig.json` though - it was completely standard after executing `tsc --init`, and was complaining that:
>No inputs were found in config file 'c:/Users/Me/source/repos/personal/my-app/tsconfig.json'. Specified 'include' paths were '[\"**/*\"]' and 'exclude' paths were '[\"./\"]'."

I've updated it to not exclude any files from compillation, with:
```
{
    "exclude": [ "" ],
    "compilerOptions": {...}
}
```
This gets rid of the tsconfig error and Zod's infered types no longer have optional properties.
