### ISSUE TITLE
How to use `zod` in a clean architecture setup?

### ISSUE THREAD

**Issue by ydennisy** [colinhacks/zod#813]
Hi @colinhacks - great lib!

I would love to use this in our project but right now I am not clear on best to structure the code so that the entities do not end up directly depending on `zod`.

Ideally the core entities should not depend on anything, here since they are defined using a zod object that seems impossible?

Thanks again!

**Comment by akomm** [comment]
```ts
type Item = {
  id: string
}
const Item: z.Schema<Item> = z.object({id: z.string()})
```

- You can inverse the dependency, so type Item is not derived from const Item, but const Item is typechecked against type Item.
- You can map schema API simply via a function & interface, hidding zod:
```ts
// use interface
type ParseItem = (v: unknown) => Item
const parseItem = (v: unknown) => Item.parse(v)
```

I guess everything else, how to make the layers should be derivable, or else make specific questions

**Comment by ydennisy** [comment]
Hi @akomm I really appreciate your reply! I have read it multiple times, but I am still missing something.

To me it feels like `Item` which is the entity is dependent on zod. You have still used zod to define that schema.

Are you saying because we then do not use `Item.parse(v)` but rather `parseItem` we do not have entities which directly depend on an external lib?

**Comment by akomm** [comment]
@ydennisy 
You have `Item` defined first. The Schema is only there to parse data, not define your entities. The `z.Schema<Item>` makes the schema definition depend on Item, not the other way around. That makes your schema be type-checked against Item, so you can't create a schema, that validates something else and the inferred type when you use the parse somewhere else will be Item.

If you want somewhere to parse the data and you don't want to depend on zod, you can depend on an interface instead and then wherever needed provide it. Hence no zod dependency, because zod is then only internal implementation detail. You could switch it for something else that can `(v: unknown) => Item

**Comment by akomm** [comment]
@ydennisy 
In my example, the Schema depends on Item, not the other way around. Schema is not there to create entities. Its there to parse them. 

The interface helps your code not to depend on zod directly all over the place. The code you want it out can just consume the interface.

**Comment by morgs32** [comment]
How can you assert the union type on an enum?

```
type IUnion = 'A' | 'B' | 'C'
export const ZEnum: z.Schema<IUnion> = z.enum([
  'A',
  'B',
  'C',
])

console.log(ZEnum.enum.A) // error: enum does not exist on ZodType
```

**Comment by akomm** [comment]
`z.Schema` is abstract interface, does not have API for the specific types. 

The solution to your problem depends on context of usage. For example you don't need to use `z.Schema`, as long as usage of ZEnum is somehow constraint to the type.

For example:
```ts
const parse = (v: unknown): IUnion => ZEnum.parse(v)
```
This will fail type check if ZEnum is not sync with IUnion. You will see the problem on use, down the line, not directly on ZEnum in this case.
