### ISSUE TITLE
extending a z.object with a refinement

### ISSUE THREAD

**Issue by blocka** [colinhacks/zod#826]
I'm upgrading my zod 2 code to zod 3.

I have something like this

```
const form = z.object({}).refine(....)
```

where I use that refine to validate field X based on Y, etc.

in some other places in code, I take that z.object and add fields to it (base z.object represents a standard form, while custom forms sometimes require custom validation), so I had something like `return form.extend(....)`

However, once I add refine to the z.object, `extend` is no longer available (according to TS)

I scanned the migration guide, and didn't see anything mentioning this.

**Comment by scotttrinh** [comment]
@blocka 

Yeah, we have several threads of discussions about this in the issues, but no clear guidance in the documentation. Apologies for that.

The basic issue is that in zod 3 we run the schema validations _first_ and then apply refinements and transformations. This avoids having issues with the type that is given to `refine` and `transform` having the wrong type at runtime due to further changes to the input schema.

There isn't an easy way to get the old behavior, but my personal suggestion (this is what me and my team do) is to export schemas and refinements separately and if something needs to extend a schema and then apply refinements or transformations, to apply it from those exported refinements.

I give some specific guidance and examples in [this discussion thread](https://github.com/colinhacks/zod/discussions/694). I'm going to close this issue for now, and feel free to continue asking questions and looking for clarifications either here or in that discussion thread.
