### ISSUE TITLE
Missing `.exclude()` with functionality of `Exclude<>` in TS

### ISSUE THREAD

**Issue by LucasForster** [colinhacks/zod#829]
Hey, first of all thanks so much for the package!

As the title suggests I'm searching for a way to replicate the `Exclude<Type, ExcludedUnion>` functionality provided by TS ([docs](https://www.typescriptlang.org/docs/handbook/utility-types.html#excludetype-excludedunion)) using `zod`. I searched for "exclude" in issues and prs, but didn't find a single mention of this utility type (outside of internals), therefore I'm opening this issue.

My use case involves unions of many smaller action types, e.g.:
`type Actions = { type: "added", ... } | { type: "removed", ... } | { type: "changed", ... } | ... ;`
(or rather an equivalent `const Actions = z.union([ ... ]);` on which I'm using `z.infer`)

I need to retroactively exclude only a few specific actions from the main `Actions` type.

Using only TS, I can add a discriminator key such as `notA: true` to those few actions and then define:
`type ActionsOnlyA = Exclude<Actions, Actions & { notA: true }>;`

Using zod, I have to add a discriminator such as `isA: true` to a lot more actions to then use:
`const ActionsOnlyA = Actions.and(z.object({ isA: z.literal(true) }));`
(I still favor this over passing additional schemas for `ActionsOnlyA` from the definitions up to the root of the project due to the amount of code.)

Maybe I'm also missing an obvious way on how to get this behavior using the existing functionality... Any advice or comment is highly appreciated :)

**Comment by codycuellar** [comment]
I was just coming over here to post the same thing, and the same goes with `Pick<type, union>`. There's a lot of cases where I have one big union, but other components only use sub-sets of that main union. All my API types are provided by passing zod schemas and then the class infers the correct return types from them, so I can't simply use pick/exclude in type parameters anywhere. For the time being I have to duplicate a lot of code to declare a new zod schema for every possible combination, rather than simply `myMainUnion.exclude([z.literal('one'), z.literal('two')])`, or substitute exclude with pick. I'm sure this is not trivial and perhaps why the functionality doesn't (yet) exist, but it would be super helpful working with unions to reduce duplicate code.

**Comment by scotttrinh** [comment]
I don't have anything useful to add other than to say we'd welcome contributions here and I'm unaware of any existing functionality that covers these use-cases. We tend the build up unions/enums by composing the smaller ones rather than trying to exclude from a main one, but I absolutely can see the use-case here. Our goal is to mimic the type system in TypeScript and `Exclude` is an incredibly useful utility.

**Comment by LucasForster** [comment]
Hey, thanks for your comments!

First let me just wrap up my use case mentioned above: It was solvable by following up the zod's `parse` with a custom type guard containing `"notA" in action && action.notA === true` (TS can't infer the type by itself using only this code).

> All my API types are provided by passing zod schemas 

This sounds like a more advanced use case actually requiring it!

> the same goes with `Pick<type, union>`

and `Extract` as well!

> we'd welcome contributions here

Unfortunately that's not gonna be me for now. How do you handle issues here? We can keep this one open as a collection, in which case probably the title should reflect all utility types mentioned, or close it 🤷🏻‍♂️

**Comment by scotttrinh** [comment]
@LucasForster 

I'm absolutely fine with leaving it open and keeping the title to be specifically about `Exclude`/`exclude` for now. I added a help wanted label and if someone has the bandwidth to add it, they can use this thread to coordinate with you and others who have a need for it. Thanks again for raising the issue and for providing use-case/context.

**Comment by schalkventer** [comment]
@LucasForster @colinhacks. I've created a custom helper function that gets me somewhat there, although there is room to improve the DX - probably by some clever usage of mapped/conditional types. However, it gets me far enough that I tend to have some success with it:

```js
const narrowEnum = <T extends z.ZodEnum<any>>(original: z.ZodEnum<any>, narrowed: T): T => {
  const originalAsArray = original.options as string[];
  const narrowedAsArray = narrowed.options as string[];

  const isMatch = narrowedAsArray.every((value) => originalAsArray.includes(value));

  if (!isMatch) {
    throw new Error(`Unable to narrow enum: ${originalAsArray} does not contain all values in ${narrowedAsArray}`);
  }

  return narrowed;
};
```

See static typing below.

![image](https://github.com/colinhacks/zod/assets/14258328/f8ba7370-9612-47e9-b2d7-78b9a2f68007)

Perhaps someone has suggestion on how the above can be built-up/improved?
