### ISSUE TITLE
object.shape is undefined when a default is specificed

### ISSUE THREAD

**Issue by WilsontheWolf** [colinhacks/zod#830]
Hello there. I have been messing around with zod and think it's quite useful. However, I have found that when using the default (and possibly other sub-methods on an object the shape property is lost.
Take this example;
```js
const object = z.object({
    test: z.string().default("Hello World"),
});

const objectWithDefault = z.object({
    test: z.string().default("Hello World"),
}).default({});

// Returns the the test object
console.log(object.shape.test);

// Shape is undefined and errors
console.log(objectWithDefault.shape.test);
```
The second one should behave much like the first. However, it does not.

**Comment by scotttrinh** [comment]
@WilsontheWolf 

This is a side-effect of how we've implemented methods that (could) affect the input -> output type. Other methods include `transform`, `refine`, etc. Those methods return a `ZodEffect` and as you've seen, they no longer contain `ZodObject` specific properties and methods due to the nature of their (possible) runtime behavior.

Depending on your use-case, you may need to export both a "base" schema and a schema that uses one of these methods if you need to do something `ZodObject`-specific. I realize that is a little frustrating in your simple example since you can tell that the `shape` should be the same. 😅

**Comment by tv42** [comment]
This just hurt me due to `.superRefine` hiding my `ZodArray`'s `element` property.

It'd be nice if ZodEffect could somehow delegate to the thing it wraps.
