### ISSUE TITLE
How to represent a React Componenet in Zod?

### ISSUE THREAD

**Issue by Brandon-Perry** [colinhacks/zod#843]
Essentially I'm defining some types and I have no clue how to tell Zod that I want something to be a ReactNode, Element, ReactChild, etc. Any idea on how to do this?

ex.

```
const higherOrderComponent = z.object({
      childComponent: ????,
})
type HigherOrderComponent = z.infer<typeof higherOrderComponent>
```

**Comment by scotttrinh** [comment]
@Brandon-Perry 

I don't have any personal experience to add here since we don't often need to check component usage at runtime, but I can picture libraries wanting to have like debug-mode checking similar to PropTypes. Nothing is (or will be) built into Zod to accomplish this, but you could create a schema that represents `ReactNode` by translating the react type definitions. If you think that's generally useful, feel free to create a library like `zod-react` and we can add a link to it in our ecosystem.

It'll be something like this:

```ts
// Based on this def:
// type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;

const reactNodeSchema = z.union([
  reactChildSchema, // left as an exercise to the reader
  reactFragmentSchema, // left as an exercise to the reader
  reactPortalSchema, // left as an exercise to the reader
  z.boolean(),
  z.null(),
  z.undefined(),
]);
```

I'm not sure if something like [`ts-to-zod`](https://github.com/fabien0102/ts-to-zod) could be useful here, but you can give that a try! I'm going to close for now, but feel free to at-mention me with any follow-up questions and if you get something working the you want us to link to, just assign me to a PR to add your repo to our ecosystem list.
