### ISSUE TITLE
Q: Partially execute a parse action

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [colinhacks/zod#853]
So using vee-validate with zod for form validation brought up a thing with how zod is used in that context. So lets take a z.object({}) with some validation rules for fields. Since there is only .parse or .safeParse and so on for the whole object, this is always applied when the form validates no matter if all those values have been changed.
This brought up a problem with legacy data that might be not valid but also not changeable.
So my question is, is it possible to define a z.object({}) but then only parse certain elements of it like z.object({a, b}).parse(data, ['a']) something like that, so instead of form validation, field validation would be possible if there was a way to partially executing a schema.
One obstacle would remain though, handling refines that have a reference to a field that is not selected have to be handled too.

**Comment by scotttrinh** [comment]
That's definitely achievable with `.partial`, but as you noted, refinements make that a bit harder. I suggested an approach on a similar issue [here](https://github.com/colinhacks/zod/issues/479#issuecomment-854822386) which embraces the potential `Partial` nature so you can reuse the same refinement function on a partial or full schema.

If you really only care about validating certain data, but don't want the other fields to be stripped from the object, you could use `passthrough` and only define the fields you care about on the schema. It would only check those fields, but the parsed data would contain any other fields which might have been defined. You have to be careful with that since TypeScript won't know anything about those other properties, but if you just need to pass it back to your backend, that _should_ be fine. If you _do_ need to use those fields, I would suggest not lying to the compiler and properly handle those "optional" fields even if you don't _want_ them to be optional.

**Comment by cefn** [comment]
I am struggling with type inference from the resulting type (Typescript cannot apparently reason about the entries from the spread operator so it doesn't understand at compile time that `message` is a field of `looseSchema`), but I think the runtime behaviour of `looseSchema` will be correct following the approach below, that allows you to base a schema on picking any parts of a schema that you want...

```typescript
import {z} from "zod";

const tightSchema = z.object({
  id:z.string(),
  rev:z.string(),
  message:z.string(),
})

const {shape} = tightSchema;

const looseSchema = z.object({
  ...shape,
  id: shape.id.optional(),
  rev: shape.rev.optional(),
})
```

**Comment by sschneider-ihre-pvs** [comment]
Thanks for the two suggestions, I will look into it.

**Comment by JacobWeisenburger** [comment]
This seems like this question was answered. May I close this?
