### ISSUE TITLE
Adding a default to a value converts its cast type to optional

### ISSUE THREAD

**Issue by PupoSDC** [colinhacks/zod#886]
This works all right:

```ts
type Potato = {
  kiwi: string,
}

const potatoSchema : ZodSchema<Potato> = z.object({
  kiwi: z.string(),
});
```

But now I would like to add an additional value as a "fallback" in case a value for`kiwi` is missing. 

```ts 
// [typescript]
// Type 'ZodObject<{ kiwi: ZodDefault<ZodString>; }, "strip", ZodTypeAny, { kiwi: string; }, { kiwi?: string | undefined; }>' is not // assignable to type 'ZodType<Potato, ZodTypeDef, Potato>'.
//   The types of '_input.kiwi' are incompatible between these types.
//    Type 'string | undefined' is not assignable to type 'string'.
//      Type 'undefined' is not assignable to type 'string'
const potatoSchemaBroken : ZodSchema<Potato> = z.object({
  kiwi: z.string().default("kiwi"),
});
```
`Z.infer` does deduce the correct type

```ts
type InferedPotato = z.infer<typeof potatoSchemaBroken>;
// Infers type correct,
// type InferedPotato = {
//     kiwi: string;
// }
```
From reading the docs, I expect that the type you get from ` : ZodSchema<Potato>` to match the type from  `z.infer<typeof potatoSchemaBroken>`. Am i missing something?

Thank you for your time! 😄

**Comment by lostfictions** [comment]
Hey there. This is the correct behaviour, and the issue is that you're using an explicit type annotation that doesn't reflect the actual type of the schema.

It can be a bit confusing at first, but Zod distinguishes between the "input type" (the type that's expected to be passed to the schema for validation) and the "output type" (the value you'll get back from parsing). In many cases input and output are the same type, but some schemas transform an input value to a different type. `.transform()` is one method that can do this, but `.default()` also does it! When a schema or field has a default, it means its _input_ can be undefined, but its _output_ is never undefined.

Your schema, `z.object({ kiwi: z.string().default("kiwi") })`, isn't actually of type `ZodSchema<Potato>`. `ZodSchema` is an alias for `ZodType`, whose definition starts like this:

https://github.com/colinhacks/zod/blob/cc8ad1981ba580d1250520fde8878073d4b7d40a/src/types.ts#L129-L133

So it actually takes different type parameters for the input and output types, but the input type defaults to whatever you tell it the output type is (which is why it doesn't complain when you pass it only one type parameter).

When you try to tell TypeScript your schema is `ZodSchema<Potato>`, you're actually saying "this is a `ZodSchema` with input type `Potato` and output type `Potato`". And that's not the case -- the input type here isn't the same as the output type, since on the input type `kiwi` doesn't need to exist.

`z.infer` gives you the type you expect because it's inferring the _output_ type. The docs mention this -- check out the ["What about transforms?" section under "Type inference"](https://github.com/colinhacks/zod#type-inference).

More generally, I really don't recommend adding an explicit type annotation when you assign a schema to a variable, like you did with `const potatoSchema : ZodSchema<Potato>`. The whole point of Zod is that it infers all of this for you, so by adding annotations you're doubling (or tripling, as you've experienced when input and output types differ) your work! It means you have to write extra code to make sure your redundant annotations sync up with the work Zod's already done for you. This is the whole reason `z.infer`/`z.output` and `z.input` exist -- you should use those instead.

**Comment by PupoSDC** [comment]
Thanks a lot for your detailed explanation! It makes a lot of sense that If I'm specifying a default value, that specific key is indeed optional.

I understand now the way Zod works, although i feel like there is a gap needing to be filled. You see, `Potato` in this case is not really a type that I own. In most of my use cases Im trying to write validation schemas that validate against an API type, which is not directly under my control. Im also not a big fan of inferring Typscript types from JS objects, and especially from validation libraries. The first is problematic because you don't really have type safety just type consistency. The second is problematic because validation libraries come and go with the wind and it's not ideal to have your types being dependent on a specific validation library. It would be nice to have something like...

```ts
const potatoSchemaBroken : ZodOutput<Potato> = z.object({
  kiwi: z.string().default("kiwi"),
});
```

where we are basically saying that if the `parse` operation works, then the resulting object is of type `Potato`.

In the end I went around this problem by not having default values initialisation as part of my schema definition. Basically something like:

```ts
const potatoSchema : ZodSchema<Potato> = z.object({;)
  kiwi: z.string(),
});

const defaultPotatoSchemaValue = {
  kiwi: "kiwi"
}

const parsedPotato = potatoSchema.parse({ ...defaultPotatoSchemaValue, ...candidateObject });
```

this might become limiting if i ever find myself with nested objects, but i will work something out when I get there.

In any case, thanks a lot for your help! Closing this, and if anything I will open a new ticket as a feature request ;)
