### ISSUE TITLE
Help users with choosing this library

### ISSUE THREAD

**Issue by konhi** [colinhacks/zod#909]
Zod is a really useful library in case of fetching data from external source! ✨

I think we could do some things that would help users to choose the best library for their case. My suggestions are:
1. move comparison section upper in readme's hierarchy, since it's more important 
1. simplify comparison section and turn it into table, [got](https://github.com/sindresorhus/got#comparison) is a good example
1. create issues in other data validation libraries and ask to also provide comparison section in theirs READMEs
1. add sample use cases, e.g. scraping websites; using external APIs

Please let me know what are your thoughts on that! 😊

**Comment by scotttrinh** [comment]
@konhi 

Great suggestions! I'm happy to help review documentation update PRs, as documentation has been something on my mind a lot lately. I'm thinking about organizing a documentation working group so that we can help coordinate any interested community members that might want to contribute docs and examples. I'll start a discussion and feel free to let us know if you'd be interested in joining!
