### ISSUE TITLE
Validate object against schema without cloning

### ISSUE THREAD

**Issue by petewest-vocovo** [colinhacks/zod#922]
Is there a way to validate an object against a schema without cloning it and returning a different object?

It would be much less computationally/memory intensive just to do the checking and not go through the process of cloning it and stripping out extra fields, which could be useful in many cases.

**Comment by scotttrinh** [comment]
> Is there a way to validate an object against a schema without cloning it and returning a different object?

Not out of the box: Zod subscribes to the [parse, don't validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) concept so it requires returning the object. Furthermore, since schemas might transform the data, it would be complicated to support returning a non-cloned copy in some cases but not in others.

If you schema does not do any transformations or preprocessing, you can write your own type guard with it, though. It doesn't fix the memory issue, but throwing away the cloned object should allow the garbage collector to collect it minimizing the impact. Just to be absolutely sure I'm clear here: _if you have transformations or preprocesses this will not work_ since the input data is not mutated by the schema.

```ts
const schema = z.object({
  foo: z.string()
});

function check<T>(
  schema: z.ZodType<T, z.ZodTypeDef, T>,
  candidate: unknown
): candidate is T {
  return schema.safeParse(candidate).success;
}

const foo = { foo: "foo" };
if (check(schema, foo)) {
  foo; // { foo: string }
}
```

> stripping out extra fields, which could be useful in many cases.

There is a [`passthrough` option](https://github.com/colinhacks/zod#passthrough) for `ZodObject` if you want to pass through the extra fields.

**Comment by petewest-vocovo** [comment]
Thanks! Really thorough and useful response!
