### ISSUE TITLE
.deepPartial() broke type-checking of arrays of objects

### ISSUE THREAD

**Issue by akanoce** [colinhacks/zod#990]
When using `.deepPartial() `in order to proagate` .partial()` to all nested objects,  the type validation of array of objects is broken.
The type checking is executed correctly using` .partial()` directly on the object.

```
object({
// ....    
questions: object({
        question_id: string(),
        response: string()
    }).array().optional()
}).deepPartial()
```

This broke the array internal type validation, allowing the parse of `[{}]`, `[{"fff": "fff"}]` and similar. 
The general array type validation seems to work correctly.

**Comment by colinhacks** [comment]
Can you provide a full example please.

**Comment by colinhacks** [comment]
This is working as intended. Deep partial makes all keys optional for all nested object types, so `{questions: [{}]}` is now a valid input. 

So is `{questions: [{}]}` because Zod allows unknown keys by default (though they are stripped out of the final result of `.parse`). 

What behavior/type are you expecting?

**Comment by akanoce** [comment]
@colinhacks  Thanks for the quick response. Sorry i just figured out what you mean, it's working correctly. I would like to apply deepPartial to a big object which include that array, without influencing it. Maybe i have to use strict() into the array? Thanks in advance

**Comment by colinhacks** [comment]
This is what `.partial` if for, if I understand you correctly.
